### ISSUE TITLE
vscode extension comments aren't supported anymore

### ISSUE THREAD

**Issue by bubblefish-dev** [SpyglassMC/Spyglass#1002]
Comments in .mcfunction files aren't highlighted as comments, commenting doesn't work unless I manually put a "#" in the beginning of each line i want to comment.

I don't use any extensions other than Data-pack Helper Plus v3.3.39, VS Code v1.74.0 64bit

**Comment by SPGoding** [comment]
Please install this extension in addition to DHP, as DHP doesn't provide language definitions for mcfunction: https://marketplace.visualstudio.com/items?itemName=arcensoth.language-mcfunction
