### ISSUE TITLE
The "darkness" effect is missing

### ISSUE THREAD

**Issue by CircusForOne** [SpyglassMC/Spyglass#1009]
Trying to use minecraft:darkness with the /effect comes up with this error message:
_Failed to resolve namespaced ID “minecraft:darkness” in registry “minecraft:mob_effect” (rule: “strictMobEffectCheck”)_

**Comment by CreeperMagnet** [comment]
Switch your Cmd Version in settings -> extensions -> datapack language server to "1.19.3"

**Comment by CircusForOne** [comment]
I checked and it is set to that. So I am assuming that the effect is missing or it's bugged.

**Comment by SPGoding** [comment]
This should've been fixed by ec22a19deb4374d3d531b736f41464967d140366.
