### ISSUE TITLE
无法在注册表中解析命名空间ID

### ISSUE THREAD

**Issue by Swampew** [SpyglassMC/Spyglass#1015]
![不能识别新物品](https://user-images.githubusercontent.com/121425045/219948498-b3ee747e-0324-4a9b-8f4c-176d46533c77.png)
![不能识别新合成类型](https://user-images.githubusercontent.com/121425045/219948450-aa03d1bd-c691-41bc-8725-ef473597c8cf.png)

这个问题困扰了我好久，但是我也一直没自己找到解决办法。尝试过重装，但是没用。

在我这边，1.19+的新内容都会出现这个问题：DHP不认识新添加的东西，会报错。

我觉得这应该不是插件的问题，应该是我本地设置的问题，我应该怎么办？

**Comment by Alumopper** [comment]
我和另一位数据包作者也遇到了相同的问题。
![image](https://user-images.githubusercontent.com/90548686/225559440-6519c23b-9a01-4cb3-80f5-390eb3f12f0b.png)
很意外居然没有其他的人提出相似的问题吗
![image](https://user-images.githubusercontent.com/90548686/225559714-e429bb53-8413-421a-83db-4391cc33b56e.png)
这个是我的配置。不知道是不是本地缓存的问题，如果是又该怎么清除呢

**Comment by SPGoding** [comment]
长城问题 😔

**Comment by JesKi13567** [comment]
这个问题我也遇到了，删了又重新下载还是没用。。
