### ISSUE TITLE
Plugin doesn't recognize dolphin's 'Moistness' as a valid tag

### ISSUE THREAD

**Issue by GrifterMage** [SpyglassMC/Spyglass#1016]
Wrote a command to summon a dolphin, but Spyglass is telling me that 'Moistness' is an unknown key--it's the value that tracks when a dolphin should take damage for being out of water too long.

**Comment by misode** [comment]
Can confirm. Even as far back as 1.14.4 dolphins have had this tag `Moistness: int`. Also worth noting is that they don't have the `CanFindTreasure` tag (anymore), unlike what [mc-nbtdoc states](https://github.com/Yurihaia/mc-nbtdoc/blob/master/minecraft/entity/mob/dolphin.nbtdoc)
