### ISSUE TITLE
IMP-doc hover doesn't show after editing a file until reload

### ISSUE THREAD

**Issue by Z0rillac** [SpyglassMC/Spyglass#1023]
The IMP-doc hover display doesn't work at all as soon as a file is modified, and only works again after reloading the page or even sometimes only works after restarting vscode. Maybe I'm doing something wrong ? Very annoying because I'm developing a library making an effort to integrate all this as well as possible because this is a very good idea.

https://user-images.githubusercontent.com/77410912/223233676-b1bc5679-c6b3-479d-a77a-58d1efe8bc6b.mp4

Here are how I implemented IMP-doc in my example :
![Capture d’écran 2023-03-06 222951](https://user-images.githubusercontent.com/77410912/223235177-655b141c-8c3a-4050-b5d5-a74bc22c4799.png)
![Capture d’écran 2023-03-06 222907](https://user-images.githubusercontent.com/77410912/223235179-c5d5c065-7451-419e-a946-d430360c9f0f.png)

**Comment by MulverineX** [comment]
This is a caching issue. Will be solved by v4.
