### ISSUE TITLE
Damage signatures are not structured properly

### ISSUE THREAD

**Issue by KevinPlayz1970** [SpyglassMC/Spyglass#1024]
The command is usually as follows:
`/damage [entity] [amount] [type] by [cause] from [assailent]`
In the datapack helper, the command is structured as followed:
`/damage [entity] [amount] [type] by [cause] [assailent]`
This makes it show as incorrect when using the proper syntax (from assailent, not just the assailent) and correct when using the inproper syntax which will not work in MC

Screenshots:
![Screenshot 2023-03-06 203806](https://user-images.githubusercontent.com/69225080/223297191-32ae7538-8697-4746-8125-50c6da125c7a.png)
![image_2023-03-06_204139412](https://user-images.githubusercontent.com/69225080/223297244-46c3b998-67f8-444a-9a40-f112a074aef4.png)

**Comment by SPGoding** [comment]
Fixed by fce2ed0755a6d8e41d761496bf13eaf9bc855a44.
