### ISSUE TITLE
Certain Display entity NBT keys are missing

### ISSUE THREAD

**Issue by SadanMasterMode** [SpyglassMC/Spyglass#1027]
Certain display entity keys (such as "item_display") show up as invalid with the datapack
This also extends to the view range which is set to a range between 0 and null which is not possible, making it error everytime
![image_2023-03-08_193056877](https://user-images.githubusercontent.com/69225080/223884134-046d49fc-d428-4c89-83bf-f081b848892a.png)
![image_2023-03-08_193114745](https://user-images.githubusercontent.com/69225080/223884171-688c297e-f256-405d-8735-87038da58ead.png)

Unsure which other ones also are invalid though you can probably double-check all of the keys in the article: https://www.minecraft.net/en-us/article/minecraft-snapshot-23w06a

**Comment by MulverineX** [comment]
Oh woops looks like I accidentally doc'd it as `alignment` 😅. And ugh open ranges in nbtdoc.

**Comment by MulverineX** [comment]
Alright well this is fixed in mcdoc, I'm no longer going to be working on nbtdoc, but we will accept PRs.

**Comment by MulverineX** [comment]
Will be fixed in v4.
