### ISSUE TITLE
newest release candidate changed start_interpolation field

### ISSUE THREAD

**Issue by SadanMasterMode** [SpyglassMC/Spyglass#1029]
Before the release candidate, the field was called `interpolation_start`
After it, the field was renamed to start_interpolation which is recognized as incorrect in the NBT of the entity
![image_2023-03-10_122305780](https://user-images.githubusercontent.com/69225080/224381901-10c69052-87b2-4c55-b6db-3a90077294ef.png)

**Comment by MulverineX** [comment]
Will be fixed in v4.
