### ISSUE TITLE
Repeated error: "Failed setting language to “en-ca”."

### ISSUE THREAD

**Issue by GrifterMage** [SpyglassMC/Spyglass#1031]
I've been getting this error thrown up repeatedly; not sure when it started. Env:Language is set to "Default", so I would assume it's happening because DHP's trying to autodetect the language it 'should' use, but then not properly validating whether or not that language is actually available before trying to use it.

> [I18N] Failed setting language to “en-ca”. Error: Cannot find module './en-ca.json'
>     at i (c:\Users\grift\.vscode\extensions\spgoding.datapack-language-server-3.4.9\dist\server.js:1:1214779)
>     at a (c:\Users\grift\.vscode\extensions\spgoding.datapack-language-server-3.4.9\dist\server.js:1:1214728)
>     at c:\Users\grift\.vscode\extensions\spgoding.datapack-language-server-3.4.9\dist\server.js:1:10932 {
>   code: 'MODULE_NOT_FOUND'

Changing Env:Language to "en" prevents the error from recurring.

**Comment by ChenCMD** [comment]
meybe related: webpack/webpack#16793

**Comment by SPGoding** [comment]
This is intended behavior. It's just logged as a warning and shouldn't affect anything.
