### ISSUE TITLE
在打开bypass_cooldown标签时dhp崩溃

### ISSUE THREAD

**Issue by CR-019** [SpyglassMC/Spyglass#1035]
如题，在打开该伤害类型标签时，dhp开始向服务器获取信息并且失败，最后报错。
此时dhp的其他功能也不可使用。
相关的日志附链接于下：
https://wwow.lanzoum.com/i7xc20qgzfha

**Comment by MulverineX** [comment]
如果 v4 发布后这仍然是一个问题，请告诉我们

(If google translate is bad: "If this is still a problem once v4 releases, let us know")
