### ISSUE TITLE
无法找到交互实体

### ISSUE THREAD

**Issue by shuangfas** [SpyglassMC/Spyglass#1043]
无法找到在23w07a中的新实体：Interaction
![2](https://user-images.githubusercontent.com/131521386/233775131-73534e55-390c-44f5-95c9-8979a7f99ad3.PNG)
![3](https://user-images.githubusercontent.com/131521386/233775137-df723a2a-dbca-4a44-b6f6-482a874941a0.PNG)

**Comment by SPGoding** [comment]
码云基本上废了，我下个版本更新下 bundled 的数据
