### ISSUE TITLE
Weird duplication replacement with nbt items

### ISSUE THREAD

**Issue by Kesuaheli** [SpyglassMC/Spyglass#1052]
It says theres was a new update just now. But it seems like it destroyed a bit of the syntax?

Im having the following command
`give @p minecraft:red_glazed_terracotta{CustomModelData:100}`
But in VSCode it looks like this: (note the color difference)
![image](https://github.com/SpyglassMC/Spyglass/assets/40177436/afb50f82-7209-41bf-86ec-911bd35985ba)
Although all lines are completly correct, after saving it gets replaced to this:
![image](https://github.com/SpyglassMC/Spyglass/assets/40177436/af714744-f1db-4b66-ba31-ddabbc1dde7a)
The complete line, exept the item itself, gets duplicated. Only the one without nbt tags stays unchanged.

I've noticed the same with the summon command. But still only when summoning an entity with nbt data.

---

I worked on a project when suddenly the autocomplete (and part of the syntax highlighting) stopped working. So I thought I might just restart VSCode and I'll be fine again. And I did.
After restarting the autocompletion and syntax highlighting worked fine again. But then I immediately experienced the described behaviour.
While I thought "well, thats strange..." I've noticed VSCode installed an update for DHP and it says "Reload required" in the extention tab. So I Restated VSCode once again. I thought "maybe its just partly installed does not work correctly yet 🤷‍♂️". But well,... that didn't seem to have changed anything. (Even restarted again after a few minutes)

**Comment by SPGoding** [comment]
Is this still an issue in 3.4.13?

**Comment by Kesuaheli** [comment]
No, its fixed. Thanks!
