### ISSUE TITLE
Some registries are no longer filled with vanilla entries

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#1055]
![grafik](https://github.com/SpyglassMC/Spyglass/assets/12124394/819bc957-d44b-444f-829f-762efeeebaec)
![grafik](https://github.com/SpyglassMC/Spyglass/assets/12124394/bc913e86-ead0-4666-bd92-df3fea27fa28)

![grafik](https://github.com/SpyglassMC/Spyglass/assets/12124394/642e5bab-6bf7-43f3-b04c-618052bfb35c)

**Comment by NeunEinser** [comment]
This seems to be the case when setting cmd and json versions to 1.19.4, but not with 1.20 / 1.20-pre1

**Comment by SPGoding** [comment]
Reverted 8adbe5360694d2b2793c0a078cffd3cb9cf72c85 at 070eb843e57596a2f20825d4e82ae6389ae75945
