### ISSUE TITLE
Data key not recognized in if statement

### ISSUE THREAD

**Issue by pauloalbert** [SpyglassMC/Spyglass#1061]
This is a valid piece of code in minecraft, run by a marker. however, DHCP v3.4.13 for 1.19.4 alerts that "name" is an unknown key:
```
execute if data entity @s data{"name":"octorok"} run function zelda:entity/enemy/octorok/create_red
execute if data entity @s data{"name":"blue_octorok"} run function zelda:entity/enemy/octorok/create_blue
```

<img width="534" alt="image" src="https://github.com/SpyglassMC/Spyglass/assets/8577984/2ec5103c-0386-46fe-a684-4f5e75224bdc">

oddly, {"name":"octo"} doesn't raise flags, when the data part is omitted

**Comment by tryashtar** [comment]
I found a couple other related cases
```
# should warn, but doesn't
data get entity @s {invalid:1}
# warns, but shouldn't
data get entity @s data.stuff[{whatever:1}]
```

**Comment by MulverineX** [comment]
Superseeded by #1112
