### ISSUE TITLE
"any_of" and "all_of" condition not recognized in predicate.

### ISSUE THREAD

**Issue by noetherianXD** [SpyglassMC/Spyglass#1064]
![bug spyglass](https://github.com/SpyglassMC/Spyglass/assets/96465019/1e0172a9-e861-4688-828f-0ec471bcc6c1)

Edit: It seems to recognize those conditions, but still gives warning.

**Comment by misode** [comment]
The default version of the extension is still 1.19.4. To change it to 1.20, go to settings:
![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/93089fb0-a3c8-4342-83ff-50e40c263e26)

```jsonc
{
    // ...
    "datapack.env.cmdVersion": "1.20",
    "datapack.env.dataVersion": "Latest release"
}
```

**Comment by noetherianXD** [comment]
> The default version of the extension is still 1.19.4. To change it to 1.20, go to settings: ![image](https://user-images.githubusercontent.com/17352009/244878617-93089fb0-a3c8-4342-83ff-50e40c263e26.png)
> 
> ```js
> {
>     // ...
>     "datapack.env.cmdVersion": "1.20",
>     "datapack.env.dataVersion": "Latest release"
> }
> ```

It was already changed to 1.20 when I noticed the error.
