### ISSUE TITLE
The falling_block has a new NBT, CancelDrop, from 1.20

### ISSUE THREAD

**Issue by Lily-bulb** [SpyglassMC/Spyglass#1068]
Thank you for letting me use it.
Starting with version 1.20 of Minecraft for the entity, falling_block, a byte type NBT called CancelDrop was added to the entity, falling_block, which when set to 1b, will not become a block when it falls to the ground of its name. It looks like that NBT has not been added to this add-on yet, so please add it if possible.
Sorry for not using tags, this is my first time using GitHub...

**Comment by Lily-bulb** [comment]
Sorry for not using tags...?, this is my first time using GitHub...

**Comment by MulverineX** [comment]
Will be fixed in v4. (fix incoming to mcdoc)
