### ISSUE TITLE
Mod command annotaion

### ISSUE THREAD

**Issue by Userhunt** [SpyglassMC/Spyglass#1073]
Create custom command and write mcfunction
#generate random value with bound 5 and store in <#random math> score
#@modCommand
modMath rand 5

Get "Invalid argument type. datapack"
McFunction file is red and have an problem
Have an 43 errors in workspace, but when load datapack, all mcfunction work correct
![изображение_2023-08-19_155901768](https://github.com/SpyglassMC/Spyglass/assets/36658653/8136e0ab-a16e-48ab-abb3-55b3db3b4b66)
I no need command parser like other command, but need to mark next line is correct

**Comment by ChenCMD** [comment]
duplicated #873
