### ISSUE TITLE
Wrong Highlighting

### ISSUE THREAD

**Issue by Dragolution** [SpyglassMC/Spyglass#1082]
Data-pack Helper Plus
VSCode

Command:
summon wandering_trader ~ ~ ~ {active_effects:[{id:"minecraft:invisibility",amplifier:1b,duration:-1,show_particles:0b}]}

Issue:
The "active_effects" gets marked as "Unknown key".

Command 2:
execute as @e[type=wandering_trader] run data merge entity @s {Offers:{Recipes:{}}}

Issue 2:
If you want to remove trades of a wandering_.trader and uses this command it tells "Expected a list tag but got a compound tag (rule: “nbtTypeCheck”)."

**Comment by MulverineX** [comment]
Will be fixed in v4.
