### ISSUE TITLE
Predicates condition do not match the datapack format (version)

### ISSUE THREAD

**Issue by benazarenko** [SpyglassMC/Spyglass#1085]
Hello. I'm creating a datapack for 1.19.4, the wiki says that pack_format should be set to 12. When I try to add a predicate with condition `alternative` it shows an error. But when I change it to `any_of` it's okay with it. But `any_of` has been added in 1.20, and in 1.19.4 the option was named `alternative`. I checked if it works in-game and it does. Looks like an issue, but maybe I've overlooked something.
![Снимок экрана 2023-10-31 143709](https://github.com/SpyglassMC/Spyglass/assets/7333912/ae7023d2-a794-46ce-823a-536228f16033)

DHP version: `3.4.18`
pack.mcmeta:
```JSON
{
    "pack": {
      "pack_format": 12,
      "description": "Test pack"
    }
}
```

**Comment by MulverineX** [comment]
Pack format resolution is broken in v3, this will be fixed in v4
