### ISSUE TITLE
Error when saving a macro mcfunction. "A request has failed." "Request textDocument/formatting failed."

### ISSUE THREAD

**Issue by Kesuaheli** [SpyglassMC/Spyglass#1089]
When saving a mcfunction file wich contains one or more macros, the formatter fails with the following error message:

> Request textDocument/formatting failed.
> 	Message: Request textDocument/formatting failed with message: t.data.map is not a function
> 	Code: -32603

When I comment out the macro line(s) it works fine.

Also I noticed if this function uses IMP documentation, it is not correctly shown while hovering a call to this function. I have to comment out the macro line(s), hit save (without the above error), and uncomment again.

**Comment by misode** [comment]
@Kesuaheli Version `v3.4.19` was just published which fixes this bug! Send your thanks to @ChenCMD!
