### ISSUE TITLE
NBT item names giving error when using correct syntax regarding italicized name

### ISSUE THREAD

**Issue by ZargetGaming** [SpyglassMC/Spyglass#1090]
Hello,

I'm working on a datapack for a 1.18.2 server and I noticed that VSCode is throwing an error ("Expected a boolean") when using quotations in the "italic":"false" nbt tag. In command blocks, and in all documentation I can find, it shows the tag requiring quotation marks around the boolean, but VSCode, or rather the DPH extension, wants me to write "italic":false without the qutation marks around the boolean.

These are the full commands I'm using:

#gives player the item with custom name
give @a[team=LifeEmpowered] minecraft:black_concrete_powder{Enchantments:[{id:"channeling",lvl:1}],display:{Name:'{"text":"Darkened Life Essence","italic":"false","color":"green"}'}}

#when item is tossed on ground, should be detected
execute as @e[type=item,nbt={Item:{id:"minecraft:black_concrete_powder",tag:{display:{Name:'{"text":"Darkened Life Essence","italic":"false","color":"green"}'}}}}, distance=..4] run say hi

With these commands, exactly as shown, the intended effects occur, and minecraft chat outputs "hi", but VSCode shows the error "Expected a boolean. datapack [Ln 1, Col 134]"

When removing the quotations from around the word false, VSCode no longer gives the error, but minecraft chat does not output "hi".

As mentioned in the title, I am in minecraft version 1.18.2. Is it an issue with me using the wrong version of DPH, or is it an actual bug?

Thanks,
ZargetGaming

**Comment by ZargetGaming** [comment]
I'm stupid, don't know how to delete the bug report

**Comment by misode** [comment]
Before 1.20.3 this syntax was allowed in text components. Since 1.20.3 you have to use `false` and `true` without quotes. DHP has never allowed them with quotes, so yeah just don't quote them.
