### ISSUE TITLE
"function" not recognized in if statement

### ISSUE THREAD

**Issue by rorybd** [SpyglassMC/Spyglass#1093]
This is valid syntax in Minecraft as of version 1.20.3. However, DHCP v3.4.18 alerts that "function" is invalid.

`execute if function`

![image](https://github.com/SpyglassMC/Spyglass/assets/124809440/1e92c21e-f9c3-4f20-9e25-1fee2fbfb776)

**Comment by misode** [comment]
@rorybd Version `v3.4.19` was just published which fixes this bug!
