### ISSUE TITLE
Provide checking & auto-complete in a new `pack.mcmeta` before a `data` folder is created

### ISSUE THREAD

**Issue by ArsiTheFox** [SpyglassMC/Spyglass#1094]
Can't get pack.mcmeta to auto-complete. I used to be able to manually type the file with auto-fill
![Code_BMEvEhhi39](https://github.com/SpyglassMC/Spyglass/assets/24835664/c58a9729-fe50-4a37-96f9-d7826363cb33)

**Comment by MulverineX** [comment]
You shouldn't need to create the `data` folder to get suggestions here.

**Comment by misode** [comment]
Unfortunately it doesn't seem like there is an easy solution to this problem. See https://github.com/microsoft/vscode/issues/193025

**Comment by misode** [comment]
A possible solution might be if we contribute a separate language and use the `onLanguage:mcmeta` activation event.
