### ISSUE TITLE
NBT validation does not recognize Type:"cherry"

### ISSUE THREAD

**Issue by Silicon-E** [SpyglassMC/Spyglass#1096]
Using DHP v3.4.19
I added this line to a .mcfunction file:
`execute if entity @s[type=boat, nbt={Type:"cherry"}] run summon item ~ ~ ~ {Item:{Count:1b, id:"minecraft:cherry_boat"}}`

I expected no error to be reported, because "cherry" is a valid boat type in Minecraft 1.20.4. (See screenshot).
![image](https://github.com/SpyglassMC/Spyglass/assets/24979888/04f23001-892d-4a57-b9df-1c804d267cd1)
https://minecraft.wiki/w/Boat#Entity_data does not list "cherry" as a valid boat type. I believe this is a mistake.

Instead, DHP underlined `"cherry"` in yellow with this mouseover message:
"Expected “bamboo”, “jungle”, “acacia”, “birch”, “dark_oak”, “oak”, “mangrove”, or “spruce” but got “cherry”."

**Comment by CreeperMagnet** [comment]
Can confirm.

**Comment by MulverineX** [comment]
Will be fixed in v4. (fix incoming to mcdoc)
