### ISSUE TITLE
Block entity NBT validation does not recognize the new "item" key from decorated pots.

### ISSUE THREAD

**Issue by CreeperMagnet** [SpyglassMC/Spyglass#1097]
```data modify storage tcc:storage root.temp.macro_input.item set from block ~ ~ ~ item```
![image](https://github.com/SpyglassMC/Spyglass/assets/45321954/b24fb5fc-ea70-4d55-803b-519cfddf408f)
![image](https://github.com/SpyglassMC/Spyglass/assets/45321954/ed82a6a6-bdb9-4902-a87b-269a0b04675e)

**Comment by MulverineX** [comment]
Will be fixed in v4. (fix incoming to mcdoc)
