### ISSUE TITLE
Macros count as error? 

### ISSUE THREAD

**Issue by amqndin** [SpyglassMC/Spyglass#1098]
I installed lsp using npm `npm i -g @spyglassmc/language-server` and set it up in neovim. now whenever i see macros being used it highlights as error, why, and how do i fix it 

![image](https://github.com/SpyglassMC/Spyglass/assets/123622161/4dba3ab4-3ea7-41f9-bab2-9c12ac88bd51)

**Comment by InQuognito** [comment]
hmm, that's a really weird issue and it doesn't look like it's part of the macro. Looks like the reader thinks create_new is a new command. Check your data version and command version and try regenerating the cache as well.

**Comment by MulverineX** [comment]
Will be fixed in v4.
