### ISSUE TITLE
Bug: Linebreaks in new version (1.20.3) don't work

### ISSUE THREAD

**Issue by Mqxx** [SpyglassMC/Spyglass#1100]
Hey I have some issues with the extension with newlines on the new version (^1.20.2).

[I have alreads filed an issue in the syntax-mcfunction repo.](https://github.com/MinecraftCommands/syntax-mcfunction/issues/9)

Linebreaks error:
![image](https://github.com/SpyglassMC/Spyglass/assets/62719703/381078a2-0609-4e9c-b307-e916eabaf7fb)

Editor:
- VSCode

Code Snippet:
```mcfunction
tellraw @a [\
  { "text":"Reloaded" }\
]
```

More information:
- "syntax-mcfunction" version: `v0.6.0`
- "Data-pack Helper Plus" version: `v3.4.19`

Selected target version `1.20.3`

**Comment by Mqxx** [comment]
Hi, any update on this?

**Comment by Mqxx** [comment]
@misode Any update on when this gets fixed?

**Comment by TheAfroOfDoom** [comment]
this should be closed since it duplicates https://github.com/SpyglassMC/Spyglass/issues/1069

**Comment by Mqxx** [comment]
> this should be closed since it duplicates #1069

Ahh okay, have not seen this. Thanks!
