### ISSUE TITLE
Several formats of NBT haven't been updated.

### ISSUE THREAD

**Issue by Vistomer** [SpyglassMC/Spyglass#1101]
In 1.20.2, some formats have changed.

Game no longer uses numeric values when storing mob effects to world.
For example, 4 becomes minecraft:mining_fatigue.
Changed following fields in mob effect instances:
Id (integer) -> id (string, resource location)
Ambient -> ambient
Amplifier -> amplifier
Duration -> duration
ShowParticles -> show_particles
ShowIcon -> show_icon
HiddenEffect -> hidden_effect
This field is a mob effect instance, so changes to the parent also applied here, recursively.
FactorCalculationData -> factor_calculation_data
In NBT format for block entity type beacon:
Primary (integer) -> primary_effect (string, resource location)
Secondary (integer) -> secondary_effect (string, resource location)

In NBT format for entity type mooshroom:
Removed EffectId, and EffectDuration.
Added stew_effects, with the same format as effects field in suspicious_stew item format.
In NBT format for entity type area_effect_cloud:
Renamed Effects to effects.
In NBT format for entity type arrow:
Renamed CustomPotionEffects to custom_potion_effects.
In NBT format for living entities (players, armor stands, and all mobs):
Renamed ActiveEffects to active_effects

But the NBT validation hasn't been updated
![image](https://github.com/SpyglassMC/Spyglass/assets/157816074/38ba4631-4984-4c79-bb2c-aa0f37e30cb4)
![image](https://github.com/SpyglassMC/Spyglass/assets/157816074/cc3b9afd-e92c-4e97-bcd4-8866b5fb6405)

**Comment by InQuognito** [comment]
this has already been implemented. Please make sure you have your data version set to the latest MC version and, if that doesn't work, regenerate your cache from the command prompt menu.

**Comment by misode** [comment]
Regenerating your cache will not refresh nbtdoc.

@Vistomer You will need to manually clear the folder for the version in `%appdata%\Code\User\globalStorage\spgoding.datapack-language-server`. After doing that and restarting vscode, it should get the updated nbtdocs.

**Comment by MulverineX** [comment]
Will be solved in v4.
