### ISSUE TITLE
I am not notified of this JSON error

### ISSUE THREAD

**Issue by Rusiink** [SpyglassMC/Spyglass#1102]
I try to run the function within the game, but it doesn't work.
Once I copy the command itself and place it in a command block, everything is marked red, evidencing that there is an error that DataHelperPlus did not notify me in the Visual Studio Code.

The error is because there are two "#" in the color of one of the texts, once I eliminate it it works correctly.

I don't know if it helps at all, I found it curious and wanted to report it.

Thank you very much for creating this beautiful tool.

Command:
execute anchored eyes positioned ^ ^ ^2 as @e[tag=entidad.id.leible,limit=1,sort=nearest,distance=..4] at @s run title @a[tag=temporal] actionbar [{"text":"🙋 🙂","color":"#00FFE5"},{"text":"  =  ","color":"##008577"},{"score":{"name":"@a[tag=temporal,limit=1]","objective":"utilizando_ID"}},{"text":"   |||   ","color":"black"},{"score":{"name":"@s","objective":"ID"},"color":"white"},{"text":"  =  ","color":"#858585"},{"text":"🔘","color":"white"}]

![1](https://github.com/SpyglassMC/Spyglass/assets/112059660/956d16dc-184f-4f18-af0d-8973fba80ee1)

**Comment by MulverineX** [comment]
Will be solved in v4.
