### ISSUE TITLE
Damage command incorrectly allows multiple entities

### ISSUE THREAD

**Issue by SimonDMC** [SpyglassMC/Spyglass#1103]
`/damage` only permits a single entity, while Spyglass allows multiple

This should show an error:
![image](https://github.com/SpyglassMC/Spyglass/assets/46278840/78731cda-162e-4296-8f68-a2f7c2022e42)

![image](https://github.com/SpyglassMC/Spyglass/assets/46278840/99554a51-5299-4327-9b16-c860c6f0fd92)

**Comment by MulverineX** [comment]
Will be fixed in v4.
