### ISSUE TITLE
Displays not recognised in syntax

### ISSUE THREAD

**Issue by Starcraft426** [SpyglassMC/Spyglass#1105]
Sometimes it works and sometimes, the displays are no longer recognised. It happened yesterday, I don't how I fixed it but it is there again and not recognised whenever I restart VsCode
<img width="1310" alt="Screenshot 2024-03-03 at 09 24 34" src="https://github.com/SpyglassMC/Spyglass/assets/57520713/034d2580-948f-4a62-9ef1-a953bd2fdf6d">

**Comment by MulverineX** [comment]
Will be solved in v4.
