### ISSUE TITLE
Feature: Idea for `#define`|`#declare` to set custom NBT-paths

### ISSUE THREAD

**Issue by Kesuaheli** [SpyglassMC/Spyglass#1106]
So I came across this notation:

![VSCode Warning saying 'Unknown key "bukkit".' while reading the `bukkit.lastKnownName` NBT Path from a player entity](https://github.com/SpyglassMC/Spyglass/assets/40177436/3df58800-98d2-47a8-8149-91bc6f99ed31)

---

(From [Discord-Message](https://discord.com/channels/666020457568403505/666020458453270535/1213400021131599892))

Syntax Idea:
Base Syntax `#define <nbt_type> <target> <path> [data_type] [values...]`

`nbt_type` specifies the type of targets this path applies to.
Possible values with examples:
- `storage_nbt`: Defining custom NBT for a storage
  - `#define storage_nbt my_cool_storage path.to.data`
- `entity_nbt`: Defining custom NBT for a given entity type
  - `#define entity_nbt player this.path.doesnt.exist.lol`
  - `#define entity_nbt marker data.importent.variable`
- `item_nbt`: Defining custom NBT for an item type (examples based on 1.20.5 components, but obviously works for older format too)
  - `#define item_nbt dirt my_mod:custom_component.data`
  - `#define item_nbt my_mod:cool_item path.to.even.cooler.data`
  - `#define item_nbt iron_pickaxe minecraft:custom_data.insert.example.here`
- `item_custom_data`: Shortcut or alias for `item_nbt` prefixed with `minecraft:custom_data.`
  - `#define item_custom_data iron_pickaxe insert.example.here` results in the same definition as the last example from `entity_nbt`
- `tile_nbt`: Defining  custom NBT for a tile entity
  - `#define tile_nbt furnace my.hot.path`
  - `#define tile_nbt chest my.not_so_hot.path`
- `block_nbt`: Alias for `tile_nbt`

Also, an option for `*` as `<target>` to apply this path to all targets of this type would be cool 
- `#define entity_nbt * path.applied.to.all_entities`
- `#define item_custom_data * is_cool`
- `#define storage_nbt * secret.data`

The optional `[data_type]` parameter defines this paths data type.
Possible values, as of current NBT specification:
- `byte`
- `short`
- `int`  | `integer`
- `long`
- `float`
- `double`
- `byte_array`
- `string`
- `list`
- `compound`
- `int_array`
- `long_array`
If omitted, any value is omitted.
Example:
- `#define item_custom_data * is_cool byte`

And my idea for `[values...]` is to list possible values this path can have. Idk if it is even possible in the current state. But to check against values would be pretty neat.
- `#define item_custom_data * is_cool byte 0b 1b`
- `#define storage_nbt * this.path string "this name" "not this name" "maybe this name too"`

**Comment by MulverineX** [comment]
Will be solved by #1112; won't use IMP Doc.
