### ISSUE TITLE
May 1.19.2(or other?) block list take error?

### ISSUE THREAD

**Issue by FlameFire26** [SpyglassMC/Spyglass#1109]
- I set the data version to 1.19.2, but found it said not found that block.
- I use Minecraft 1.19.2 to catch screen
- I'm already restarted VSCode to reload

<img width="593" alt="1" src="https://github.com/SpyglassMC/Spyglass/assets/122438076/cca2495d-cba4-484c-9a33-b0bcb1dfdbb7">
<img width="674" alt="2" src="https://github.com/SpyglassMC/Spyglass/assets/122438076/f4482846-7cc4-4a00-834a-562743d5231a">
<img width="417" alt="3" src="https://github.com/SpyglassMC/Spyglass/assets/122438076/f097f7e0-df02-4d36-842d-c0b605c927b4">

**Comment by MulverineX** [comment]
This is a cache bug and is partially due to the legacy system of not using pack format. Will be fixed in v4.
