### ISSUE TITLE
Add support for custom mcdoc definitions

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1112]
This will grant the ability to document `data storage`, marker `data`, item `custom_data`, and modded entity/block/item data.

```[tasklist]
### Tasks
- [ ] `mcdoc` folder at root of a pack
- [ ] Git repositories listed in workspace/global settings
```

**Comment by SPGoding** [comment]
i believe it already parses `mcdoc` files found in the workspace, and there is special handling for a subfolder named `mcdoc` to treat that folder as the root path for mcdoc files.

**Comment by MulverineX** [comment]
Yeah this is totally already a thing, going to make another issue for the external definitions feature
