### ISSUE TITLE
Not recommending Display entities

### ISSUE THREAD

**Issue by YocraftGG** [SpyglassMC/Spyglass#1115]
When I type "summon" it doesn't recommend block_display, item_display, and text_display

**Comment by MulverineX** [comment]
![image](https://github.com/SpyglassMC/Spyglass/assets/12068027/51535931-7891-4fbd-8c6a-5d97873f7dd0)
These need to be set to the version you're using

**Comment by YocraftGG** [comment]
I didn't understand, where did this screenshot come from?

**Comment by YocraftGG** [comment]
I use the latest version (1.20.6). And the highest here is 1.20.3

**Comment by MulverineX** [comment]
You probably have the outdated cache issue. Press Ctrl+J and select Datapack Language Server, scroll all the way up, and there should be a path printed where it stores the cache. Open that folder and delete the 1.20.3 folder there. Then reload vscode.
![image](https://github.com/SpyglassMC/Spyglass/assets/12068027/8dd8c191-c414-4938-be4b-68edb48d3654)

**Comment by YocraftGG** [comment]
Now that I opened what you said I see all kinds of messages like: [VanillaData: BlockDefinition for 1.20.6] Fetching from undefined, so maybe that's the issue.
![‏‏צילום מסך (2)](https://github.com/SpyglassMC/Spyglass/assets/145869035/42e393ec-d4e8-4d91-99a0-81f9813f1b14)


In any case, when I open the folder I see a folder of 1.20.2, of 1.20.4 and of plugins

**Comment by MulverineX** [comment]
@YocraftGG delete the 1.20.2 & 1.20.4 folders

**Comment by YocraftGG** [comment]
didn't work
I will totally understand if you don't want to continue helping me,
Basically, I can manage anyway.
Thanks anyway
