### ISSUE TITLE
Since 1.19.3, many of entities or blocks cannot be recognized.

### ISSUE THREAD

**Issue by JesKi13567** [SpyglassMC/Spyglass#1116]
- DHP ver 3.4.19
- MC ver 1.20.3

There's a list for unrecongized things: (not all)

- Spawn Eggs: ender_dragon|iron_golem|snow_golem|wither|camel|sniffer...
- Blocks: bamboo-style blocks|cherry-style blocks|chiseled_bookshelf|hanging signs|head of piglin...
- Entities: entity display(for 3 types)|interaction|decorated pot|suspicious sand/gravel|torchflower...

Anyway, hope all of this could be added.
```[tasklist]
### Tasks
```

**Comment by SPGoding** [comment]
This will be solved with the release of v4.
