### ISSUE TITLE
NBT tag for minecraft:interaction is not recognized

### ISSUE THREAD

**Issue by tombo512** [SpyglassMC/Spyglass#1120]
Ver. 3.4.19
CMD version 1.20.3

The unique NBT tags for minecraft:interaction (height, width, response, attack, interaction) are not recogunized and the warning occurs.

ex) execute at @s run summon minecraft:interaction ^ ^ ^1 {height:2}
-> warning: "height" : Unknown key.

**Comment by MulverineX** [comment]
This will be solved with the release of v4.
