### ISSUE TITLE
Make `loadLocale()` fall back gracefully when locale has subtags

### ISSUE THREAD

**Issue by SPGoding** [SpyglassMC/Spyglass#1134]
Current Behavior:

* Call `loadLocale('en-us')`
* It throws an exception because there is no language file `en-us.js`

Expected Behavior:

* Call `loadLocale('en-us')`
* It should try to load `en-us.js` and fail
* It should try to load `en.js` (with `-us` subtag removed) and succeed

**Comment by TheAfroOfDoom** [comment]
why isn't the English locale just called `en-us.json` in the first place?
