### ISSUE TITLE
References to use statements aren't being resolved properly by mcdoc yet

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#1154]
![image](https://github.com/SpyglassMC/Spyglass/assets/12124394/94123201-584e-43a9-a100-9385243ba1a0)
![image](https://github.com/SpyglassMC/Spyglass/assets/12124394/45c0a360-03fc-4f4f-85fe-a5907cc582ba)
![image](https://github.com/SpyglassMC/Spyglass/assets/12124394/6a6b5749-f7b0-4748-848d-39586b97ba78)

The use statement itself is properly resolved to the definition, but when referencing it somewhere, you get a reference with the same name but the path of the current module.

This eventually leads to `options.context.symbols.query(ctx.doc, 'mcdoc', '::java::data::predicate::Predicate')` being resolved as a union of `(::java::data::predicate::LootCondition | [::java::data::predicate::LootCondition])` which itself is not a valid mcdoc reference.

```
use super::loot::LootCondition

type Predicate = (LootCondition | [LootCondition])
dispatch minecraft:resource[predicate] to Predicate
```

**Comment by SPGoding** [comment]
This is intentional, so when you Ctrl+click `LootCondition` it goes to the `use` statement first, and Ctrl+click again goes to the actual definition. The `use` statement introduces the referenced symbol into the current scope under a new symbol path and is a valid reference.

**Comment by NeunEinser** [comment]
In that case, the use statement fails to create a reference. In the registry, the lookup of `::java::data::predicate::LootCondition` yields no result.
