### ISSUE TITLE
Fix advancement "display" object structure for 1.20.6

### ISSUE THREAD

**Issue by SolusBellator** [SpyglassMC/Spyglass#1194]
After my server throwing an error on reload, claiming there's `No key id in MapLike[{"item":"minecraft:compass"}]`, I took a look at a foreign datapack for 1.20.6, and found that the structure of the advancement display object has changed slightly.

The current version expects it to be:

```json
"display":
{
    "item": "minecraft:compass"
}
```

However, the new format (not even mentioned in the wiki, but I can confirm it works in 1.20.6) expects:

```json
"display":
{
    "id": "minecraft:compass"
}
```

so currently when building for 1.20.6 

1. there's no completion as the field is not recognized
2. all advancement files throw the same error (`Missing key: "item"`)

Hope this isn't a duplicate, but couldn't find any other issue on this.

I know, data format changes are annoying, and this isn't super high priority, but it'd still be nice to have it fixed with the next update.

**Comment by misode** [comment]
The currently released version of DHP (v3) only supports versions up to 1.20.4. We're currently in the process of a rewrite which will solve this issue. You can follow the progress here: https://github.com/SpyglassMC/Spyglass/milestone/41
