### ISSUE TITLE
Ensure all translation keys have English locale strings available

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1199]

**Comment by NeunEinser** [comment]
I recently changed localizer to return the key when there is no localization found. Perhaps it would be good to wrap it into something, maybe return `<key>`, so it's easier to spot?

Ideally, we would have some CLI which maybe collects all strings that are passed into localize and sees if they exist, but not sure how feasible that is.

**Comment by MulverineX** [comment]
That could just be implemented like this https://github.com/SpyglassMC/Spyglass/pull/1192

**Comment by MulverineX** [comment]
This isn't how this will be implemented
