### ISSUE TITLE
Mark that 1.20.5+ won't be supported until rewrite is done is VSCode extension page

### ISSUE THREAD

**Issue by WithLithum** [SpyglassMC/Spyglass#1200]
The 1.20.5+ support have been, according to various issues closed here like #1194 and #1108, delayed _until the Spyglass rewrite is complete_. I suggest to mark this out in the marketplace pages of legacy extension, as there are no mentions to the rewrite yet, and it does not seem it will ever come out before The Next Big Version.

Major versions that have passed:
- 1.21 Tricky Trials

**Comment by TheAfroOfDoom** [comment]
i actually have no idea how to update the marketplace page, i incorrectly assumed it was a file in the repo but cant seem to find that now.

probably something only @SPGoding can do?

**Comment by TheAfroOfDoom** [comment]
we have a beta version for v4.0 in the Discord now so i'm closing this issue
