### ISSUE TITLE
Allow modded command tree patches to be configured in settings

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1207]
As a successor to #873, this allows people who feel like adding command tree patches for modded commands to do so, under a specific namespace that users must enable in extension settings.

Inspired/justified by this existing: https://github.com/misode/misode.github.io/tree/master/src/app/partners

**Comment by MulverineX** [comment]
(I commit to doing this eventually, unless someone else wants to sooner)

**Comment by SPGoding** [comment]
_it's already implemented_

https://github.com/SpyglassMC/Spyglass/blob/6103be7f90eb5583997ae14e28c807e156e63b3e/packages/core/src/service/Config.ts#L71-L81

https://github.com/SpyglassMC/Spyglass/blob/6103be7f90eb5583997ae14e28c807e156e63b3e/packages/java-edition/src/dependency/index.ts#L121-L129

**Comment by MulverineX** [comment]
I'm silly
