### ISSUE TITLE
Anoying directory change for datapack versions 45+

### ISSUE THREAD

**Issue by ninjaguardian** [SpyglassMC/Spyglass#1214]
This snapshot changed names for directories so the plugin won't work.
[Changelog](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w21a#:~:text=directory%20renames)

**Comment by SPGoding** [comment]
The currently released version of DHP (v3) only supports versions up to 1.20.4. We're currently in the process of a rewrite which will solve this issue. You can follow the progress here: https://github.com/SpyglassMC/Spyglass/milestone/41

**Comment by misode** [comment]
This issue tracking this change is #1169
