### ISSUE TITLE
Support testing multiple versions in argument parser tests

### ISSUE THREAD

**Issue by Calverin** [SpyglassMC/Spyglass#1215]
Should be set to 1.21 and generated test snapshots should be updated, requires changes to `mockProjectData` in `packages/core/test/utils.ts`

**Comment by misode** [comment]
The 1.15 version was added as part of #1179 (https://github.com/SpyglassMC/Spyglass/pull/1179/commits/c8981602b2232a820097d1df0df220a0de9c0717). See also my comment on #1202:
> I looked at the tests for a bit but I didn't see a good way to test these parsers in multiple versions. Right now `mockProjectData` is hardcoded to 1.15. This might be something to do in a later PR.
