### ISSUE TITLE
Add mcdoc support for JSON tag files

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1217]
For this, the `tag_entry` mcdoc attribute will have to be implemented first.

**Comment by misode** [comment]
We don't want to create a mcdoc type for every registry in vanilla-mcdoc

**Comment by NeunEinser** [comment]
Why would that be needed? Not trying to argue against it, I just don't understand the problem, or the proposed solution. Can you give an example?

**Comment by misode** [comment]
This is our current `Tag` definition in `vanilla-mcdoc`:
```rs
dispatch minecraft:resource[tag] to struct Tag {
	replace?: boolean,
	values: [TagEntry],
}

type TagEntry = (
	#[tag_entry] string |
	#[since="1.16.2"]
	struct {
		id: #[tag_entry] string,
		required?: boolean,
	} |
)
```
How would you rewrite this to not use the `tag_entry` attribute, but still avoiding a separate `dispatch` for every registry? In your `#id[foo, allow_tags=true]` example earlier, what would `foo` actually be?

**Comment by NeunEinser** [comment]
`foo` would be something like `minecraft:block`, for a block. I guess it wouldn't really be that simple as it's usually a block id, block tag, or list of blocks now.

I guess you are talking about actual tag files? Yeah for these you'd need a separate definiton per tag then, I guess. How are you avoiding that with `tag_entry` though? How does `tag_entry` know which tag type it is targeting?

**Comment by misode** [comment]
> How does tag_entry know which tag type it is targeting?
When creating the adapter/options object, it would dynamically construct a `tag_entry` handler that knows what registry the tag is. At least that's my idea.

**Comment by MulverineX** [comment]
Depends on #1225
