### ISSUE TITLE
Use the `minecraft:resource` mcdoc dispatcher for JSON file validation

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1218]
Right now the mcdoc identifiers are hardcoded for each file category, it should use the mcdoc dispatcher to figure out the right identifier.

**Comment by NeunEinser** [comment]
Can you give an example for such a hardcoded identifier? I am unsure if you mean the dispatcher entries themselves, the dispatcher names, or something else I am not thinking about.

For the two I named, I don't know how you would avoid hardcoding.

**Comment by misode** [comment]
The `Checkers` map in `java-edition/src/checker/index.ts`
```ts
const Checkers = new Map<core.FileCategory, `::${string}::${string}`>([
	['advancement', '::java::data::advancement::Advancement'],
	['dimension', '::java::data::worldgen::dimension::Dimension'],
```

`vanilla-mcdoc` has all this information:
```rs
dispatch minecraft:resource[advancement] to struct Advancement {
```

**Comment by NeunEinser** [comment]
Ahh, that makes srnsr!

**Comment by MulverineX** [comment]
We also have to add a `pack` field to these, for now `resource_pack` will go unused

**Comment by misode** [comment]
It's fine to keep pack.mcmeta hardcoded. It will always stay as a special case.

**Comment by MulverineX** [comment]
I'm talking about dispatches to `minecraft:resource` that aren't in the datapack
