### ISSUE TITLE
Add mcdoc based completers for `runtime` doc use (JSON/NBT, etc)

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#1226]
See also #947

This issue is more about providing a general interface for mcdoc-based completers that can be reused for JSON and NBT. This may be done at once to have a test case or separately

**Comment by MulverineX** [comment]
Depends on #1225

**Comment by misode** [comment]
While working on the JSON completer, I realized that there is not much to reuse between the completers, because they much closer work with AST nodes. I opted for a reusable `getFields(type: McdocType): string[]` (simplified) function which the completers will use.
