### ISSUE TITLE
Feature Request: Self-made rules like ESLint

### ISSUE THREAD

**Issue by alinco8** [SpyglassMC/Spyglass#1233]
It would be great if custom plugins, like those in ESLint, could be used,
and those plugins could utilize an Abstract Syntax Tree to throw errors and warnings.

I understand that this would be challenging, but having such a mechanism would be very beneficial.
Thank you for creating such a wonderful extension!

**Comment by misode** [comment]
v4.0 will have a linting syntax like shown below, where you could customize when to show warnings. Do you have a specific linting rule in mind that you want to customize?

![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/3e32cd44-6290-4066-a45b-639dc3bb83e1)

**Comment by alinco8** [comment]
I didn't know such a feature existed, thanks!
