### ISSUE TITLE
我遇到了问题

### ISSUE THREAD

**Issue by lenyuxuanwww** [SpyglassMC/Spyglass#1251]
set_nbt会报错——选项“minecraft:set_nbt”无效。
![FB01ED3C0AC5C260B37AAB265530B424](https://github.com/SpyglassMC/Spyglass/assets/62456934/1699e0e6-30e2-4556-89c6-1aad9b09e138)

**Comment by MulverineX** [comment]
![image](https://github.com/SpyglassMC/Spyglass/assets/12068027/bc9c08bf-7008-463f-9fdc-1b8a15b68c72)

Looks like this is not an issue with [upstream](https://github.com/misode/minecraft-schemas).

I'm guessing this is 1.20.5+ minecraft schemas, are you using 1.20.4 or below?


我猜这是 1.20.5 版本的 minecraft 模式，您使用的是 1.20.4 或以下版本吗？
使用 DeepL 翻译

**Comment by MulverineX** [comment]
在 1.20.5 中，删除了 set_nbt，代之以 item_components 和 custom_item_data。当前版本的扩展不支持该版本及以后的版本。一旦 Spyglass/v4.0 发布，这些版本将得到正式支持。
使用 DeepL 翻译

**Comment by lenyuxuanwww** [comment]
我使用的是1.20.4，这个问题有时会出现有时又不会出现




H.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SpyglassMC/Spyglass"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 上午9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SpyglassMC/Spyglass] 我遇到了问题 (Issue #1251)





 
image.png (view on web)
 
Looks like this is not an issue with upstream.
 
I'm guessing this is 1.20.5+ minecraft schemas, are you using 1.20.4 or below?
 
我猜这是 1.20.5 版本的 minecraft 模式，您使用的是 1.20.4 或以下版本吗？
 使用 DeepL 翻译

**Comment by MulverineX** [comment]
> I'm using 1.20.4 and this problem sometimes occurs and sometimes it doesn't!
> Translated using DeepL

Ah so it's an intermittent issue! Hmm

Can you upload & send the datapack(s) you're having this issue with?


能否上传并发送遇到此问题的数据包？
使用 DeepL 翻译

**Comment by lenyuxuanwww** [comment]
[q.zip](https://github.com/user-attachments/files/15799466/q.zip)

**Comment by MulverineX** [comment]
I'm looking into this, will get back to you eventually.

我正在调查，最终会给您答复。
使用 DeepL 翻译

**Comment by lenyuxuanwww** [comment]
好的。感谢

**Comment by MulverineX** [comment]
It appears that this is purely an issue with v3 caching, there's no other way to explain the intermittent issues here.
This problem is fixed in version 4 of the extension, which is nearing completion. You can track progress here: https://github.com/SpyglassMC/Spyglass/milestone/41

看来这纯粹是 v3 缓存的问题，没有其他方法可以解释这里的间歇性问题。
扩展的第 4 版已修复了这个问题，该版本即将完成。你可以在这里跟踪进度： https://github.com/SpyglassMC/Spyglass/milestone/41

使用 DeepL 翻译
