### ISSUE TITLE
Attach type info and run string attacher on keys

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1263]
Right now the `stringAttacher` option is only called for values, not for keys. This is required for complex field keys with an `id` attribute. Example: `components` map in `set_components` loot function.

This is not super trivial to do, it looks like the checker graph is missing some information here, possibly as a result of #1248

**Comment by NeunEinser** [comment]
This should be pretty easy, as when the children nodes in checkShallow are assigned a definition, we do have access to the runtime definition as well.
