### ISSUE TITLE
Run mcdoc checker in `nbt=` selector argument

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1271]

**Comment by MulverineX** [comment]
`(::java::server::world::entity::EntityBase | minecraft:entity[%fallback])`

**Comment by misode** [comment]
> `(::java::server::world::entity::EntityBase | minecraft:entity[%fallback])`

I just modified `vanilla-mcdoc` so all entities inherit `EntityBase`, so `minecraft:entity[%fallback]` should be enough
