### ISSUE TITLE
Index map issue with nested strings

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1296]
This needs to be investigated

```
summon cow ~ ~ ~ {CustomName:'{"text":"hello","hoverEvent":{"action":"show_item","value":"{id:\'acacia_boat\'}"}}'}
```

![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/7008c366-8380-49a2-a3ff-63b4b961324a)

**Comment by misode** [comment]
I found another case where it went wrong:
![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/4e66fa98-1bbb-498f-b2cf-b8d460f20bcc)
Interestingly, it works correctly when using only double quotes:
![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/009cd5eb-617d-438b-8b7f-f32aa20b89b0)

**Comment by TheAfroOfDoom** [comment]
from https://github.com/SpyglassMC/Spyglass/pull/1355#issue-2365408905

> ![](https://private-user-images.githubusercontent.com/13565346/341597309-396ad3ce-ebfd-4891-b933-55ee4a914c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDcwMTUsIm5iZiI6MTcxOTAwNjcxNSwicGF0aCI6Ii8xMzU2NTM0Ni8zNDE1OTczMDktMzk2YWQzY2UtZWJmZC00ODkxLWI5MzMtNTVlZTRhOTE0YzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIxNTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDg3OTg3MTFkODgwN2ZmOTMxN2NiYzE2YzZmMmQwNWI4ZTQ5MmIwZmYwYmU5YWEyM2I3YmUzYzZmMWE2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2PXuYlaXM53vSK4vhNwcnBZVQOprJ92AD2KojJjaJgY)

this is a log of index maps when the `core.string` parser (?) is called.

you can see that at some point it's not actually receiving the old index map properly. i think it should be an ~easy-ish fix just need to figure out exactly where to connect prior index maps to the new one
