### ISSUE TITLE
References to structure nbt files are never found. 

### ISSUE THREAD

**Issue by jacobsjo** [SpyglassMC/Spyglass#1312]
It seems that the structure nbt files are not loaded at all, so all references to them from template pools and fossil features always get a `"Cannot find structure “[...]” (rule: undeclaredSymbol)"` warning.

![image](https://github.com/SpyglassMC/Spyglass/assets/10163794/774893b6-db62-42fa-a34e-962b71351fac)

**Comment by MulverineX** [comment]
Apparently not actually fixed

**Comment by misode** [comment]
Fixed again in aab722bff5a45ff5ce63669026463caef78a38f2
