### ISSUE TITLE
Support multi-folder workspaces

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1354]
![image](https://github.com/SpyglassMC/Spyglass/assets/12068027/5fa1a085-4df5-4d26-a828-690d1473da28)

Posted by `@minihilly` on discord, only the first pack, `Core` is being handled by the extension

**Comment by SPGoding** [comment]
Only the first workspace folder is ever used: https://github.com/SpyglassMC/Spyglass/blob/main/packages%2Flanguage-server%2Fsrc%2Fserver.ts#L89. Proper support for multi-root opens a can of worms of supporting different pack formats (and even different Spyglass config files) at the same time.

**Comment by MulverineX** [comment]
IMO, for now, we should just opt to use first root's spyglass config & pack format

**Comment by misode** [comment]
This might not be code that we want to touch in 4.0 though, for stability reasons

**Comment by MulverineX** [comment]
@SPGoding depending on whether it is too difficult to implement for v4.0 I'll change the milestone here

**Comment by tryashtar** [comment]
As a use case, my repo (https://github.com/tryashtar/shulker-preview) contains different versions of the packs for each Minecraft version. Does this count as multiple roots or not? Either way, pack format is different, so would be swell if each one worked individually and simultaneously.

**Comment by SPGoding** [comment]
That does not count as multi-root. Multi-root is a VS Code feature where multiple workspace folders are open. That is a single workspace folder with multiple data packs inside, which the current implementation should have some basic support for (probably not gonna do well with the mixed versions though).

**Comment by MulverineX** [comment]
My idea is essentially to pretend as if a multi-root *is* the latter

**Comment by TheAfroOfDoom** [comment]
my project has a multi root workspace where one of the roots is purely a subfolder access within another root for convenience. I wonder how spyglass would function in that case

**Comment by TheAfroOfDoom** [comment]
I think having an explicit config to pack mcmetas would probably make this pretty easy no? if it's a one-time config for users I don't think it's worth trying to figure out an automatic solution

**Comment by TheAfroOfDoom** [comment]
i've been using my pack again recently with spyglass and i'm not having any trouble with the workspace being multiroot. e.g. functions are being bound to the symbol table as expected

**Comment by misode** [comment]
> my project has a multi root workspace where one of the roots is purely a subfolder access within another root for convenience

@TheAfroOfDoom This the reason it works for you. Right now only paths in the first workspace folder are processed by the URI binder and cached.

**Comment by misode** [comment]
An initial attempt was made in #1378, but that will not be merged before the 4.0 release
