### ISSUE TITLE
Ability to Toggle Minecraft Namespace Autocompletion

### ISSUE THREAD

**Issue by catter1** [SpyglassMC/Spyglass#1415]
When typing in registry names (items, features, tags, etc), Spyglass will autocomplete it without the `minecraft:` namespace before it, unless explicitly typed.

It would be nice to have an extension setting to force the autocompletion of the namespace where applicable. I know it's a niche feature request, but hey, I like having everything look the same!

**Comment by catter1** [comment]
Note: In instances such as referencing components in `data` commands, the namespace is *required*. ([see this discord message](https://discord.com/channels/666020457568403505/1255970681930252320/1256542689248149514)). So at the very least, it should be autocompleted by default where it is required. I wrote this issue when thinking of JSON, where it is optional.

**Comment by InQuognito** [comment]
lol i’m the same way, i never use the auto complete for the minecraft registry because i want the namespace. i second this

**Comment by SPGoding** [comment]
It's already implemented. Set `lint.idOmitDefaultNamespace` to `false` in `spyglassmc.json`.
