### ISSUE TITLE
Crash when no workspace folders are open

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1424]
To reproduce:
1. Open a new empty vscode window
2. Run the `Spyglass: Open Cache Folder` command to activate the extension
3. Notice that the language server crashes

![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/6ecf024e-8e9c-433b-8a45-406d1ec8cfd1)

**Comment by IwrsTheKing007** [comment]
The same thing happens if you just open a .mcfunction file on its own

![image](https://github.com/SpyglassMC/Spyglass/assets/53910323/b5159df7-5898-44ed-90c7-594bfbfa917a)

**Comment by IwrsTheKing007** [comment]
also happened when I opened pack.mcmeta on its own

**Comment by betterworld-sjq** [comment]
Same problem here.

**Comment by misode** [comment]
Fixed in 212cb71c14d3135ce55dddf1967d591a224cc55d, which will be released in `v4.0.1` on the marketplace in a few minutes
