### ISSUE TITLE
Namespace warn

### ISSUE THREAD

**Issue by JustJabka** [SpyglassMC/Spyglass#1425]
![image](https://github.com/SpyglassMC/Spyglass/assets/117545035/bd77d2d3-b33b-4e98-ba8a-11d46b30ae12)
I just upgraded to version 4.0.0, reloaded VS code several times, but still the extension warns about namespaces for no reason.

**Comment by misode** [comment]
What are the warnings that you're getting? To troubleshoot, try the following:
* Make sure the `pack_format` in your `pack.mcmeta` is set to the matching version that you're using (48 for 1.21)
* Run the `Spyglass: Reset Project Cache` command

**Comment by JustJabka** [comment]
pack_format is set to 48, after writing the command and reloading the VS code, nothing has changed, the extension still warns about namespaces

**Comment by misode** [comment]
Can you show a screenshot of the warning message you're getting?

**Comment by JustJabka** [comment]
![Code_K8OGBeApLD](https://github.com/SpyglassMC/Spyglass/assets/117545035/1ad3d6e0-e82d-48a5-8c53-dbfe9de7d32c)

**Comment by misode** [comment]
Are you by change using multiple workspace folders? Rather than a single workspace folder containing multiple data packs? And this data pack is not the first entry?

**Comment by JustJabka** [comment]
![Code_K8OGBeApLD](https://github.com/SpyglassMC/Spyglass/assets/117545035/1ad3d6e0-e82d-48a5-8c53-dbfe9de7d32c)

**Comment by JustJabka** [comment]
I only have two namespaces: minecraft and survival_rework_jj. There are no other datapacks in the workspace

**Comment by JustJabka** [comment]
I figured out what's causing this error! If you try to open the "saves/<world>/datapacks/<datapack>" folder instead of the "saves/<world>/datapacks" folder, you will get this warn

**Comment by misode** [comment]
Since the project path contained square brackets, I'm pretty sure this was the same issue as #1601
