### ISSUE TITLE
`infinite` duration for effects in not recognized

### ISSUE THREAD

**Issue by RevolvingMadness** [SpyglassMC/Spyglass#1427]
Spyglass doesn't recognize the `infinite` duration for effects.
And gives the error `Expected <seconds: integer>`

![image](https://github.com/SpyglassMC/Spyglass/assets/83436020/34a1bb42-1e7a-4931-ad9f-c27105cdb15f)

**Comment by misode** [comment]
Check that your `pack_format` is set to the right value (at least `12` if you want to use `infinite`)

**Comment by RevolvingMadness** [comment]
I see. I'm using `MC Datapack Utility` to create datapacks and it creates datapacks with version `7` so I guess I'll change that in the future when I'm creating datapacks.
