### ISSUE TITLE
Weird "expected nothing" error for NBT paths

### ISSUE THREAD

**Issue by tryashtar** [SpyglassMC/Spyglass#1439]
These commands
```mcfunction
data get entity @p asdf
kill @a[nbt={asdf:[{}]}]
```
tell me "expected nothing," a strange kind of message.

![image](https://github.com/SpyglassMC/Spyglass/assets/26075577/69786a5c-209a-495a-b53a-de495790fc65)

Extension version: `v4.0.0`
Pack format: `48`

**Comment by misode** [comment]
This seems to have been caused by <https://github.com/SpyglassMC/vanilla-mcdoc/commit/89c6b84fff9e7744d1e2e609fc57f57d739a731a>. I'm not sure if it'll be possible to keep these dispatchers without any changes to the mcdoc checker...

**Comment by misode** [comment]
I reverted that commit, which returns this back to the expected behavior. We'll investigate ways to allow people to add fields to a tag in the future.
![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/166dc974-7eba-4764-a25d-7664175a97b7)
