### ISSUE TITLE
Require "limit=1" in text component "score"

### ISSUE THREAD

**Issue by tryashtar** [SpyglassMC/Spyglass#1443]
The `score` text component has some very special behavior. It accepts any string as the `name` field. If it's a valid selector, it parses and caches it, otherwise it leaves it alone. Then, at runtime, if `name` is `*` and there's an entity resolving the text, it uses that entity's score, if present. If `name` is a valid selector, it runs it. If more than one entity is found, an error is thrown. If exactly one entity is found, it uses that entity's score. If `name` isn't a valid selector, it uses that fake player's score. If a score is ever not found, it just shows no text instead.

As a result, though it's not a syntax error, I suggest that, in addition to the selector validation Spyglass already does for `name`, that it include the requirement that it's a single selector, just like in other commands with this requirement such as `/data`. Note that other text components that use selectors, like `selector` and `nbt / entity` can handle multiple results just fine.

Example command:
```
tellraw @a {"score":{"name":"@e","objective":"test"}}
```

Extension version: `v4.0.0`
Pack format: `48`

**Comment by misode** [comment]
Fixed in 75feefbdede965b28928b2513e38ebdf4bba6f24, after also adding this config to vanilla-mcdoc
