### ISSUE TITLE
Error when trying to modify some structure block NBT

### ISSUE THREAD

**Issue by Dahesor** [SpyglassMC/Spyglass#1448]
![image](https://github.com/SpyglassMC/Spyglass/assets/72520668/1ee2ad82-230b-40ec-ae9c-4a2e738e4b99)

When you try to modify the "mirror" or "rotation" NBT of a structure block, the following errors appear:

![image](https://github.com/SpyglassMC/Spyglass/assets/72520668/6eee19ec-cdca-4136-ab01-5141cd33cc3b)

I do not know if these 2 NBT are the only ones this bug affects

Thanks

**Comment by misode** [comment]
This looks like the same internal issue as #1437
