### ISSUE TITLE
Advancement command criterion checking

### ISSUE THREAD

**Issue by tryashtar** [SpyglassMC/Spyglass#1454]
```mcfunction
advancement grant @s only adventure/adventuring_time blahblah
kill @s[advancements={adventure/adventuring_time={blahblah=true}}]
```

These commands are invalid because that advancement doesn't contain a criterion called "blahblah"

Spyglass could both suggest and validate these criteria names as found in the advancement definition (and for the selector version, make sure there are no duplicates!)

**Comment by misode** [comment]
Duplicate of #883
