### ISSUE TITLE
Unknown key "components"

### ISSUE THREAD

**Issue by PilkeySEK** [SpyglassMC/Spyglass#1459]
![grafik](https://github.com/SpyglassMC/Spyglass/assets/156579268/542406ff-c014-496a-b273-ffa91f793a9d)
This might have been reported before though
Using version `4.0.1-beta` of Spyglass

**Comment by misode** [comment]
Looking at the screenshot, either the language server hasn't fully finished loading yet, or a wrong MC version is detected. If your `pack_format` is correctly set, try running the `Spyglass: Reset Project Cache` command and wait until the language server is fully responsive.

**Comment by PilkeySEK** [comment]
Well, i used overlays for 1.20.2 and 1.20.6, so that might be an issue

**Comment by misode** [comment]
Ah, the extension doesn't support multi-version packs and overlays yet, see #1071
