### ISSUE TITLE
datapack helper does not recognize minecraft 1.20 commands

### ISSUE THREAD

**Issue by MatthiasFreiburghaus** [SpyglassMC/Spyglass#1465]
to reproduce this issue, set pack_format in the pack.mcmeta file to 15, corresponding to minecraft version 1.20, and create a mcfunction calling  the following command 
`give @s bow{display:{Name:'{"text":"special bow","italic":false}'}} 1`

**Comment by misode** [comment]
Could you try reloading vscode after changing the pack_format?

**Comment by MatthiasFreiburghaus** [comment]
Yes, I did.  As a result, the command was slightly modified to 
`give @s bow{display:{Name:'{"text":"special bow","italic":false}'}}  count: 1` ,
and the complaints by datapack helper went away. So the issue should probaly considered to be resolved.
