### ISSUE TITLE
Can't detect namespace

### ISSUE THREAD

**Issue by OverFloyd** [SpyglassMC/Spyglass#1468]
Hello, after updating from 3.4.19 to v4.0.1 one specific namespace of my data pack doesn't get recognized by the extension (out of all of them).
![Screenshot 2024-07-03 185422](https://github.com/SpyglassMC/Spyglass/assets/46049254/b505bc50-21a9-4438-84f0-e58faaba9922)

Anyone know why? Thanks for the patience.

**Comment by misode** [comment]
If you hover over the first character in this file you will notice that it expected the files to be in folder `function`, because the currently loaded version is 1.21. Check that you have the correct `pack_format`. And keep in mind that the current version is lacking support for multi-version packs.

**Comment by OverFloyd** [comment]
I was aware of the 1.21 changes and I tried renaming it but nothing changes. Also, the other namespaces use functions and they have no issues.
Pack format is 48.
Also ye I don't care about multiversion support, it's just for my own sp world so it just uses whatever is the current version.

**Comment by misode** [comment]
Try running the `Spyglass: Reset Project Cache` command

**Comment by Kesuaheli** [comment]
Pack format `48` means it is ment for 1.21 ([see MC wiki](https://minecraft.wiki/w/Data_pack#Pack_format)).
So using a folder named `functions` (plural) is wrong. If your pack is ment for 1.21 it should be named `function`.
If is not, you should adjust the 48 to the correct format version and restart VSCode to reload the highlighting.

**Comment by OverFloyd** [comment]
@misode yeh might be a cache issue, renaming the whole namespace to something else makes it work. Sorry for the noobie question but how (or where) do I run said command?

**Comment by misode** [comment]
You can do so from the command palette: `Ctrl+Shift+P` and then searching for the command

**Comment by OverFloyd** [comment]
Yeah I found it and it *magically* worked, thanks for the patience :^)
