### ISSUE TITLE
Scoreboard "objective_criteria" does not have entries such as "teamkill.<team_color>" and "killedByTeam.<team_color>" and an error occurs

### ISSUE THREAD

**Issue by Ho9tocraft** [SpyglassMC/Spyglass#1474]
As the title says, I have no idea how to write "spyglass.json" or where to put it, and the site that explains it is still under construction, so I am unable to do anything about it.

**Comment by MulverineX** [comment]
The Spyglass config goes at the root of your workspace. We will investigate this report soon

**Comment by Ho9tocraft** [comment]
The problem with Spyglass.json has been solved, but still the problem as described in the title has not been solved. if you say you can solve the problem with mcdoc, I would like to ask you to improve the wiki. As it is now, it is more likely that beginners will be confused.

**Comment by MulverineX** [comment]
This is a bug with the extension, not with vanilla-mcdoc nor mcmeta.

**Comment by Ho9tocraft** [comment]
Could a hotfix-like version update reflect this as soon as possible? The teamkill and killedByTeam errors continue to occur even after Release 4.1.0 has been applied, because the changes that are currently scheduled to be applied in Release 4.2.0 have not yet been reflected.

**Comment by MulverineX** [comment]
We should probably release 4.2 soon yeah, I'll try to push it along

**Comment by Ho9tocraft** [comment]
It has been two weeks since I heard back from them that they will be released soon. But what is the reality? The number of open issues is only increasing, and nothing has been reflected in the VSCode extension.
This has not resolved the bug reports received from users, and the errors still continue to appear. If the merge is done, it would be easy to release it as a hotfix already. Even if they are stuck in the review process, it would be easier to pass this as a stand-alone fix.
Of course, we are aware that they have their own circumstances, and we understand that they would like to add and improve functions all at once and only fix bugs.
Even so, this bug needs to be fixed and patched as soon as possible. As a developer of data packs.
I hope you will do your utmost to fix this bug, including moving up the schedule.

**Comment by TheAfroOfDoom** [comment]
@Ho9tocraft please be patient. this team consists entirely of volunteers and most of us have been on vacation.

we plan on releasing a new patch soon to include some new features and fixes
