### ISSUE TITLE
start_interpolation only accepts positive integers

### ISSUE THREAD

**Issue by MrAwesomeLuigi** [SpyglassMC/Spyglass#1476]
attempting to modify the start interpolation of a display entity and it says that it expects at least 0, despite -1 being a valid option
![image](https://github.com/SpyglassMC/Spyglass/assets/81497673/2ba560e2-8c13-430b-9dcc-d92eb566f89f)

**Comment by NeunEinser** [comment]
Is there any functional difference between using -1 or 0?

Our aim is to also catch issues where you are trying to do something nonsensical, even if it is technically accepted by the game.

**Comment by MrAwesomeLuigi** [comment]
minecraft wiki says that "Trying to set a value less than 0 sets it to the current game time."
these commands are exported by animated java so its not directly by me, although id like it to not be flagged

**Comment by Nico314159** [comment]
@SnaveSutit It appears this concerns you

**Comment by SnaveSutit** [comment]
I technically already reported this issue.

https://discord.com/channels/666020457568403505/666037123450929163/1256780446512185476

![Screenshot_20240704_162519_Discord.jpg](https://github.com/SpyglassMC/Spyglass/assets/28514936/b9728f9d-439e-4f74-81bc-bc27663c6f0c)
