### ISSUE TITLE
Command "attribute" has wrong syntax in auto-complete and correct syntax is marked as wrong

### ISSUE THREAD

**Issue by koukirocks** [SpyglassMC/Spyglass#1478]
The command "attribute" should look like the following in Minecraft Version 1.21, if using modifier : 
`attribute <target> <attribute> modifier add <id> <value> <add_value | add_multiplied_base | add_multiplied_total>`
e.g. `attribute @p minecraft:generic.jump_strength modifier add bunny 1 add_value`
However in auto-complete and error highlighting, the plugin is still using the old version of the command, which is : 
`attribute <target> <attribute> modifier add <uuid> <name> <value> (add | multiply | multiply_base)`
This is making my correct code full of error, and I would like to see it fixed.
Thank you for your work.

**Comment by misode** [comment]
It's working correctly for me. Check that your pack_format is set to `48` to match 1.21
