### ISSUE TITLE
Error at renaming any folders inside the workplace

### ISSUE THREAD

**Issue by KelloVerra** [SpyglassMC/Spyglass#1479]
**Short Description**
After updating VSCode to the latest version; 1.91.0, i noticed that renaming *folders* specifically take a very long time, and then it after all the waiting, throws an `Error: EPERM: operation not permitted, rename <file_name_0> -> <file_name_1>` error in the notification menu, i thought this was a windows security problem but then i realized that after disabling the extension, renaming works fine.

**Problem**
When renaming any folder in the workspace, it will take a long time for it and then throws an error in the notification `Error: EPERM: operation not permitted, rename <file_name_0> -> <file_name_1>`.

**How to reproduce**
- Make sure the vscode version is 1.91.0
- Rename any folders
- Wait for around a minute
- Notification menu will pop out with the described error

**Note**
For some reason, naming files works fine.

**VSCode's About**
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by misode** [comment]
Duplicate of #1414
