### ISSUE TITLE
Functions from protected directories are not recognized

### ISSUE THREAD

**Issue by LeonardsWorld** [SpyglassMC/Spyglass#1482]
I am working on a datapack and am using Animated Java. AJ uses protected directories within it, and any other functions that reference functions in those protected directories are flagged as referencing a function that doesn't exist, resulting in an incessant error that I can't remove.
Please at least add the ability to dismiss errors, or the ability to flag a folder so it doesn't have any error messages.

**Comment by NeunEinser** [comment]
What do you mean by "protected directory"?

**Comment by TheAfroOfDoom** [comment]
probably this? https://learn.microsoft.com/en-us/defender-endpoint/controlled-folders#windows-system-folders-are-protected-by-default

**Comment by LeonardsWorld** [comment]
yeah

**Comment by misode** [comment]
@LeonardsWorld Can you give us a way to reproduce the issue? I still have no idea why some of the folders in your data pack are "protected".

**Comment by LeonardsWorld** [comment]
make a project using the Animated Java plugin for Blockbench in 1.20 (the folder names aren't fully updated to 1.21 yet so this is easier), export, then open any function within the animated_java/functions directory that references another function.

**Comment by misode** [comment]
It seems to work fine for me
![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/8354a86e-f500-4669-9596-44e8560d573c)

**Comment by TheAfroOfDoom** [comment]
@LeonardsWorld 

> AJ uses protected directories within it

i don't know what this means i think this is not true.

> using the Animated Java plugin for Blockbench for 1.20

if you are using the AJ beta (mc 1.20 and prior) with 1.21+ functions, you are going to get issues.

if you want to use 1.21 with AJ you need to use the 1.0.0 prereleases. latest: https://github.com/Animated-Java/animated-java/releases/tag/v1.0.0-pre11

let us know if this resolves your problem. nothing specific to AJ should break Spyglass (it hasn't for me)

**Comment by LeonardsWorld** [comment]
alright. I think I'm just doing something wrong, but it would be convenient to have an error dismissal feature.
