### ISSUE TITLE
[Error - 15:29:33] Stopping server failed   Message: Pending response rejected since connection got disposed   Code: -32097 

### ISSUE THREAD

**Issue by clunsdy315** [SpyglassMC/Spyglass#1492]
i open vscode and i find this
![image](https://github.com/SpyglassMC/Spyglass/assets/152574204/6440df4a-8ce5-4485-acdf-65266431c89e)

**Comment by clunsdy315** [comment]
datapack helper's version is 4.1.0,downgrade to 3.4.18 can fix it but i don't wanna do it

**Comment by misode** [comment]
Is that the only text in the output log or is there move above it?

**Comment by clunsdy315** [comment]
yes only text.but now i open vscode i can't find it

**Comment by misode** [comment]
Is the extension now working for you?

**Comment by clunsdy315** [comment]
no it error again

**Comment by clunsdy315** [comment]
this text is in "output"

**Comment by clunsdy315** [comment]
now it is saying "Initializing Spyglass…"

**Comment by misode** [comment]
@clunsdy315 Could you share the full output log of the language server?

**Comment by clunsdy315** [comment]
emm...i already share it

**Comment by misode** [comment]
I mean the full log file. We don't really have much information to work with

**Comment by clunsdy315** [comment]
ok

**Comment by clunsdy315** [comment]
[2-Spyglass Language Server.log](https://github.com/user-attachments/files/16219588/2-Spyglass.Language.Server.log)
[3-Spyglass Language Server.log](https://github.com/user-attachments/files/16219596/3-Spyglass.Language.Server.log)

**Comment by clunsdy315** [comment]
hello？

**Comment by misode** [comment]
It looks like the extension has trouble downloading necessary resources from `raw.githubusercontent.com`. Is this blocked in your country? Maybe you can change some DNS/network settings?
![image](https://github.com/user-attachments/assets/72fedccc-daec-430f-9bcb-e7b260c2f0df)

**Comment by clunsdy315** [comment]
thank you!
