### ISSUE TITLE
`profile="PlayerID"` shouldn't be mark as an error

### ISSUE THREAD

**Issue by AlexCai2019** [SpyglassMC/Spyglass#1493]
You can use `give @s player_head[profile="Notch"]` in game.
![image](https://github.com/SpyglassMC/Spyglass/assets/89138532/ae84ebd7-e3c8-4777-9f31-824b2b6190d2)

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/dcf85e8d4659b50f08f434e28994ed9c8ac35a02
