### ISSUE TITLE
Error when attempting to exclude default item components using !

### ISSUE THREAD

**Issue by thesorcell** [SpyglassMC/Spyglass#1496]
![spyglassreport](https://github.com/SpyglassMC/Spyglass/assets/93102875/aac7d0d6-5a0c-477a-87fc-473aeb069aa0)

Spyglass does not yet support the exclusion of default item components. This functionality was added in 24w18a, and is functional in the 1.21 release.

**Comment by NateKootstra** [comment]
I am unsure as to how I would go about testing this, however I believe that replacing the declaration of LegalResourceLocationCharacters in **packages/core/src/parser/resourceLocation.ts** with the following should solve this issue:

export const LegalResourceLocationCharacters = new Set([
	'a',
	'b',
	'c',
	'd',
	'e',
	'f',
	'g',
	'h',
	'i',
	'j',
	'k',
	'l',
	'm',
	'n',
	'o',
	'p',
	'q',
	'r',
	's',
	't',
	'u',
	'v',
	'w',
	'x',
	'y',
	'z',
	'0',
	'1',
	'2',
	'3',
	'4',
	'5',
	'6',
	'7',
	'8',
	'9',
	'_',
	'-',
	'.',
	'!',
])

**Comment by NateKootstra** [comment]
I am unsure as to how one would go about testing this, however I believe that replacing the declaration of LegalResourceLocationCharacters in **packages/core/src/parser/resourceLocation.ts** with the following should solve this issue:

`export const LegalResourceLocationCharacters = new Set([
'a',
'b',
'c',
'd',
'e',
'f',
'g',
'h',
'i',
'j',
'k',
'l',
'm',
'n',
'o',
'p',
'q',
'r',
's',
't',
'u',
'v',
'w',
'x',
'y',
'z',
'0',
'1',
'2',
'3',
'4',
'5',
'6',
'7',
'8',
'9',
'_',
'-',
'.',
'!',
])`

If anyone knows how to go about testing this change, please let me know. While I'm fairly confident that this should fix the issue, I'm not sure what the ramifications of this solution would be, and there is likely a better one. I would love to test it further.

**Comment by NateKootstra** [comment]
After looking into the issue a bit more, I think that this solution should work. If anyone would like to verify whether or not this would work it'd be greatly appreciated. Unless someone points out a flaw or proposes a better solution I plan on opening a pull request.
