### ISSUE TITLE
Particle command incorrectly expects block_state from other particles

### ISSUE THREAD

**Issue by thesorcell** [SpyglassMC/Spyglass#1497]
![image](https://github.com/SpyglassMC/Spyglass/assets/93102875/132aff0e-1f0d-4ceb-802e-b238cf8c8030)

In game, the dust particle uses color and scale, but Spyglass expects block_state. This also applies to the entity_effect particle and possibly others. This worked in Spyglass 4.0.1, if that's useful for debugging

**Comment by misode** [comment]
I believe this is caused by a caching bug that is also affecting several other places

**Comment by misode** [comment]
@thesorcell A fix for this issue has been released as `v4.1.2`!
