### ISSUE TITLE
False "expected nothing" error when using NBT.

### ISSUE THREAD

**Issue by dragon3025** [SpyglassMC/Spyglass#1502]
When I use NBT as a target selector I get an "Expected nothing" error:
![Screenshot (106)](https://github.com/SpyglassMC/Spyglass/assets/11652210/a72f5bd8-e893-4a94-90a3-20fb294ea898)

I tested it out `execute as @e[type=!#minecraft:immune_to_oozing, nbt={active_effects:[{id:"minecraft:oozing"}]}] run say test` and it was working fine. I also tested out `execute if entity @e[type=pig, nbt={PersistenceRequired:1b}] run say persistent` and it was also working fine, but it visual studio code was showing the same error, so I think it's happening if you use anything for nbt.

**EDIT**: The yellow error for `schedule function server:second 1s`, is saying that it cannot find the function, which is also false because the function is continuously running every second.

**EDIT**: Okay, I just realized it's doing when using Nbt for anything (for example: summoning a mob). Even if it's just brackets with nothing in it.

**Comment by misode** [comment]
@dragon3025 Hey, I cannot reproduce the issues you're having. Could you provide the output log of the spyglass language server? You can get that by pressing `Ctrl+Shift+U` and then selecting `Spyglass Language Server` in the dropdown

**Comment by dragon3025** [comment]
> @dragon3025 Hey, I cannot reproduce the issues you're having. Could you provide the output log of the spyglass language server? You can get that by pressing `Ctrl+Shift+U` and then selecting `Spyglass Language Server` in the dropdown

Here's the log: https://pastebin.com/3vaCmenp

**Comment by misode** [comment]
I see the warnings `Tried to access unknown dispatcher minecraft:entity` which are not normal. Can you try running the `Spyglass: Reset Project Cache` command? If that doesn't work, run the `Spyglass: Open Cache Folder` command, close vscode, delete everything in that cache folder, and reopen vscode again.

**Comment by dragon3025** [comment]
I tried both, but it's still happening. This is the log I got after deleting everything in the cache folder and re-opening vscode: https://pastebin.com/u7tRJvGi

**Comment by NeunEinser** [comment]
Is your datapack publicly available, or would you be able to share it for us to see if we can reproduce it with your pack?

**Comment by dragon3025** [comment]
> Is your datapack publicly available, or would you be able to share it for us to see if we can reproduce it with your pack?

I have an example pack here: https://modrinth.com/datapack/end-gateway-placer. When I load the folder in visual studio, I get this error:
![Screenshot (108)](https://github.com/user-attachments/assets/c1fdb128-949c-4bc7-a2c4-2fab0610f6f0)
Here's the log for it: https://pastebin.com/swGCHUv0

**Comment by MulverineX** [comment]
Are you on discord? Would you be up for a voice call? It would be useful to be able to debug this live with you.

**Comment by misode** [comment]
@dragon3025 Could you share your users settings? Or disable all your user settings? If that doesn't fix it, try also disabling all other extensions.

**Comment by dragon3025** [comment]
I figured it out. I have this .gitignore file:

    Server/
    zzz*/
    *(Edited)/

For some reason the `Server/` line in it was causing this. If fixed it by changing the line to `Server_Pack/`, renaming my Server datapack the same way, then opening visual studio code. I'll attach a copy of my datapack folder.
[datapacks.zip](https://github.com/user-attachments/files/16199337/datapacks.zip)
