### ISSUE TITLE
`%unknown` index no longer returns a union of all members

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1504]
**To reproduce:**
1. Use 1.20.4 (pack format 26)
2. ❌ Type `give @s iron_pickaxe{CanDestroy:[]}` and notice that the type of the entire compound is `any`
3. ✅ Type `give @s bat_spawn_egg{CanDestroy:[]}` and notice that it validates and autocompletes fine
4. ✅ Use the `set_nbt` loot function and notice that the NBT is checked as expected 

The reason this happens is because `iron_pickaxe` is not found in the `minecraft:item` mcdoc dispatcher. Previously, this would result in a union of all members, but now it just returns the fallback case `any`.

**Comment by NeunEinser** [comment]
This was an intentional change. Do we want to change the fallback case back to returning a union of all members?

**Comment by NeunEinser** [comment]
https://discord.com/channels/666020457568403505/666037123450929163/1254118975915294862

**Comment by misode** [comment]
> This was an intentional change. Do we want to change the fallback case back to returning a union of all members?

@NeunEinser In that case, is there a way we can fix this in vanilla-mcdoc, so that `give @s iron_pickaxe{CanDestroy:[]}` is still validated?

**Comment by MulverineX** [comment]
Yeah, by dispatching ItemBase to `%unknown`

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/3a9efbb443f2902f4cb1f8c241b65da8b3f38d06
