### ISSUE TITLE
Display completion from the end for very long symbols

### ISSUE THREAD

**Issue by TheAfroOfDoom** [SpyglassMC/Spyglass#1507]
My project has admittedly unreasonably long function paths. This ends up making the completions for some functions unusable when I'm typing out e.g. a new function call

![image](https://github.com/SpyglassMC/Spyglass/assets/13565346/8c463fb7-45ef-4bc7-88e4-7b84d96984c8)

one potential solution for this is, for extremely long symbols (maybe only functions?), display starting at the end of the symbol instead of from the beginning

**Comment by misode** [comment]
Duplicate of #1324
