### ISSUE TITLE
Text component in text_display entity is auto-completed as a compound tag rather than json in string

### ISSUE THREAD

**Issue by WithLithum** [SpyglassMC/Spyglass#1508]
The extension suggests the `text` tag in the `text_display` NBT as a compound tag rather than a JSON text included in string, and even hints the yellow color.

However, the following code, written with auto-complete, does not work in game (results in empty display) and should have been syntax error, let alone being auto-suggested in the first place:

```mcfunction
summon minecraft:text_display -552.51 -19.71 -514.00 {text:{text:"[Press to Activate]",color:yellow},Tags:["lobby_display"]}
```

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/839ca2912080f03bcba2275f6625ec48d7647fee

You can reload vscode to get these changes.
