### ISSUE TITLE
Text component in text_display entity is not validated

### ISSUE THREAD

**Issue by WithLithum** [SpyglassMC/Spyglass#1509]
The `text` tag in the following display entity is not valid and should have been syntax error:

```mcfunction
summon minecraft:text_display -552.51 -19.71 -514.00 {text:'{"text:"[Press to Ac:"yellow"}',Tags:["lobby_display"]}
```
However there are none:

![image](https://github.com/SpyglassMC/Spyglass/assets/37800788/52e2682b-9edf-4f3a-9992-2d0e00aa3a3d)

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/839ca2912080f03bcba2275f6625ec48d7647fee
