### ISSUE TITLE
The "loot_table" type of Loot table has key "name" instead of "value" in new versions

### ISSUE THREAD

**Issue by Dahesor** [SpyglassMC/Spyglass#1514]
The "loot_table" type of loot table allows player to reference another loot table. In 1.21, it uses the key "value" instead of "name".

Currently spyglass only accepts "name" for all versions.

![image](https://github.com/SpyglassMC/Spyglass/assets/72520668/b847b42b-1496-406b-add5-e247cee94c19)

![image](https://github.com/SpyglassMC/Spyglass/assets/72520668/4b0845e5-f8a4-4350-a13a-6d0a57a35b7d)

Thanks

**Comment by NeunEinser** [comment]
Looks like Spyglass is detecting the wrong version.

What is your `pack_format` in `pack.mcmeta` at?

**Comment by misode** [comment]
Can you try running the `Spyglass: Reset Project Cache` command?

**Comment by tryashtar** [comment]
Yes #1212
