### ISSUE TITLE
`$` in score holders are not escaped correctly in auto-complete

### ISSUE THREAD

**Issue by muotian** [SpyglassMC/Spyglass#1518]
As shown in the image, the auto-completion suggested the score holder defined elsewhere. But after hitting tab or clicking the option, it becomes a backslash.
This seems to affect any JSON format, including raw JSON text format.

![image](https://github.com/user-attachments/assets/17329ea7-a4c8-4526-a503-f58579125caa)
![image](https://github.com/user-attachments/assets/4f1a8f3b-f6df-4e1d-a79d-4fc2fcc37b46)

`{
  "condition": "value_check",
  "range": 0,
  "value": {
    "type": "score",
    "score": "objective",
    "target": {
      "type": "fixed",
      "name": ""
    }
  }
}`

**Comment by misode** [comment]
(dev note) This may be caused by us not escaping the `$` in the insert text
