### ISSUE TITLE
ArmorItem wildcards marked as error

### ISSUE THREAD

**Issue by MiraculixxT** [SpyglassMC/Spyglass#1520]
Entity NBT check for ArmorItems displays an error when only using one entry as wildcard.

## Current behavior
`execute if entity @s[nbt={ArmorItems:[ { count:1b } ]}]`
Marked with `Expected collection length to be at least 4 and at most 4` which is not true as a statement. Only entering one value will act as a wildcard, meaning that selector is true for every entity that has an item matching the predicate in any armor slot.

## Expected behavior
No error is shown when entering less than 4 armor item slots in a selector/check.

## Additional Screenshots
Minecraft behavior
![grafik](https://github.com/user-attachments/assets/f0692658-4fdd-430c-bea0-4f74f3cb6500)

Spyglass error
![grafik](https://github.com/user-attachments/assets/c1856c9c-a85b-45ca-a479-f658a17c8fd2)

**Comment by MulverineX** [comment]
If this is in 1.20.5+ you should probably use `execute if items` instead for better performance. Regardless this is a bug so thank you for the report.
