### ISSUE TITLE
Cache invalidation and/or clearing isn't really working properly

### ISSUE THREAD

**Issue by Kazii78** [SpyglassMC/Spyglass#1525]
![grafik](https://github.com/user-attachments/assets/b4c7a7a0-5052-45b0-bd57-9883df296d86)
![grafik](https://github.com/user-attachments/assets/2451a87e-4a60-4021-9739-c1782efc88a7)

Last thing I remember doing is zipping this data pack up VSCode Archive , put it into my Downloads folder, then put it in a new datapacks folder.

I have tried:
- clearing the cache
- going into the cache folder and deleting everything
- disabling and re-enabling the extension
- uninstalling and reinstalling the extension
- uninstalling, deleting the cache folder and extension folder in .vscode
- closing the workspace and re-opening it
- switching to a lower or higher directory
- running VSCode as administrator
- EDIT 3: closing the workspace, resetting cache, removing trust, re-opening workspace, giving back to trust

I had this one time and a simple fix was to delete the file and remake it.
I know I'm not doing that here.

EDIT 1: For clarification, this happens with every file in the data pack.
Other data packs seem to be fine.

EDIT 2: Newly made data packs have the same issue now.

EDIT 4: Completely changing the workspace directory resolves the issue. Old workspace directory still encounters the same issue.

**Comment by MulverineX** [comment]
Apologies for this, other users have had similar issues, hopefully our core maintainers can track down the root of this problem and fix it.

**Comment by misode** [comment]
Assuming this was fixed
