### ISSUE TITLE
@n selector is not recognized

### ISSUE THREAD

**Issue by theknewgreg** [SpyglassMC/Spyglass#1527]
The extension considers the new @n selector to be an invalid entity selector. It doesn't impede anything, but it results in all my function files being filled with false errors

**Comment by Calverin** [comment]
Check that you have the correct pack format in your `pack.mcmeta`. It should be 48 for 1.21

**Comment by TheAfroOfDoom** [comment]
you can also see what `pack.mcmeta` Spyglass found by opening the output log and searching for "pack.mcmeta" towards the top

```
[je.initialize] Found a valid pack.mcmeta file:///...
```

**Comment by theknewgreg** [comment]
So, it seems the problem was that one of my datapacks had the pack format 41, which it was going with. Kind of weird, since the datapack before it was format 12 (I wasn't actively editing it, it was only in there to reference old code but I would've assumed it either picked the first one or the largest numbered one. Either way, that fixed it)
