### ISSUE TITLE
`findPackMcmeta()` checks files by depth redundantly

### ISSUE THREAD

**Issue by TheAfroOfDoom** [SpyglassMC/Spyglass#1528]
this function is meant to check all the files at depths 1, 2, and 3 (from the workspace root) for a valid `pack.mcmeta` file to use.

https://github.com/SpyglassMC/Spyglass/blob/cfa732191f3896cdf8b65cca1a3351ad76e16680/packages/java-edition/src/index.ts#L43-L53

it _technically_ does this right now, but the problem is that for some depth `N`, `getAllFiles()` returns _all_ the files from depth `1..N`. what ends up happening is:

- depth: 1 -> check files at depth 1
- depth: 2 -> check files at depth 1 (again), then depth 2
- depth: 3 -> check files at depth 1 (again), then depth 2 (again), then depth 3

this is due to how the `globby` package returns a list of files for some depth; it returns files _up to_ that depth, not files _at_ that depth

this should be refactored so it doesn't re-check over the same files redundantly

https://github.com/SpyglassMC/Spyglass/blob/cfa732191f3896cdf8b65cca1a3351ad76e16680/packages/core/src/common/externals/NodeJsExternals.ts#L87-L91

---

(this probably doesn't have a _huge_ performance impact, but it's just ugly behavior anyway)

**Comment by misode** [comment]
This is not an issue. It already has a visited set to keep track of the Uri's it has tried

**Comment by TheAfroOfDoom** [comment]
ah I see. woops
