### ISSUE TITLE
not all components are recognized

### ISSUE THREAD

**Issue by Leroidesafk** [SpyglassMC/Spyglass#1531]
if I want to give myself a carrot that isn't edible, Spyglass will send me back an error

![image](https://github.com/user-attachments/assets/b824eb4e-7616-42f1-9b07-782597a8300d)

![image](https://github.com/user-attachments/assets/0fa27bd9-9290-4035-99df-e0ef2e00166e)

**Comment by misode** [comment]
Duplicate of #1496
