### ISSUE TITLE
Unable to add components to ArmorItems without problems

### ISSUE THREAD

**Issue by LambdaPod** [SpyglassMC/Spyglass#1532]
Whenever I try to add the components key to an item in an entities ArmorItems, it returns a problem, as shown below.
![Screenshot 2024-07-17 at 8 53 03 PM](https://github.com/user-attachments/assets/f66c811e-601f-4f96-99dd-6c15cccbaa9c)

**Comment by MulverineX** [comment]
What is your pack format?

**Comment by LambdaPod** [comment]
My pack format is 48, the wiki for pack format says that that's the latest version.

**Comment by misode** [comment]
@LambdaPod Are you still experiencing this problem in the latest version of the extension (v4.2.1)? If so could you share the output log of the language server? You can get this by running the `Spyglass: Show Output` command.
