### ISSUE TITLE
Spyglass thinks pack_format only supports 48?

### ISSUE THREAD

**Issue by fullwoodenshovel** [SpyglassMC/Spyglass#1540]
I'm making a datapack for 1.20.4 (pack_format 26), but Spyglass automatically underlines the 26 as yellow. I've tried numbers 1-50 to see if this is a problem with me choosing the wrong pack format, but after realising it only accepts 48 (1.21) I've been really confused. I checked back at the wiki to see if my pack format was wrong, but it confirms that 26 is indeed 1.20.4 ([here](https://minecraft.wiki/w/Pack_format)). This is troubling because it now thinks that it is using 1.21 commands, thinking the new item nbt is correct, however for my use case it isn't (because I'm still on 1.20.4). I've tried adding a `spyglass.json` with the gameVersion set to 1.20.4, but this doesn't seem to change anything, even after restarting VSCode.
Any help would be appreciated, thanks.

**Comment by fullwoodenshovel** [comment]
After having this issue for about an hour, it just fixed itself... randomly... I didn't restart VSCode, I didn't reload the extension, I didn't even change to a different file. It just... fixed...

**Comment by NeunEinser** [comment]
The yellow underline is supposed to tell you about a current technical limitation of Spyglass. If you hover over it, it should say something like that the pack format doesn't match what Spyglass has loaded, and you might need to restart vscode fir the changes to appl,  so Spyglass can reinitialize and load the correct version.

It seems this message is confusing a lot of people though.

**Comment by fullwoodenshovel** [comment]
It seems like it sometimes does it and sometimes doesn't...
Here are two images to elaborate and hopefully stop some confusion:
![image](https://github.com/user-attachments/assets/5393b264-8b45-49eb-a530-e3f6f176c9dc)
![image](https://github.com/user-attachments/assets/0a36c484-7a11-4e90-9a66-25a0a2848b1a)
