### ISSUE TITLE
Directories check hardcoded to new updates.

### ISSUE THREAD

**Issue by ElitoSear** [SpyglassMC/Spyglass#1542]
Even though I'm specifying the version 1.19.4 on my spyglass,json file I'm getting this warning.
![pasted](https://github.com/user-attachments/assets/d2a06b43-d22f-4e0c-8b42-05ee9ec490f9)

**Comment by MulverineX** [comment]
Try restarting VSCode?

**Comment by misode** [comment]
@ElitoSear Are you still experiencing these problems?
