### ISSUE TITLE
Spyglass checks for the tag directory rather than tags

### ISSUE THREAD

**Issue by RoarkCats** [SpyglassMC/Spyglass#1543]
When all the plurality was removed from the data sections, `tags` was the only one to remain plural, however, it seems this was overlooked

![image](https://github.com/user-attachments/assets/19196830-8ad2-40d0-8184-30e99a1c8ebf)
![image](https://github.com/user-attachments/assets/8f53e7a9-7d7b-431b-a2f1-e2ca1c91c4e6)

**Comment by Nico314159** [comment]
I can’t reproduce this issue, but I would suggest clicking on the file in question (sometimes Spyglass doesn’t realize the file exists until it is opened). If that doesn’t work, try reloading your window

**Comment by Nico314159** [comment]
> Odd, and no neither of those work to fix the issue, my only guess is that there's something weird going on with my tags folder as when I try to rename it specifically in VSCode the program is unable to and hangs on that task until I restart/close it, though it does finish renaming it when closed. I have no idea if that is related to Spyglass, VSCode, or my system, but it may be that Spyglass is confused about the directory for some reason

Hmm, the renaming problem might be related to #1414....

**Comment by RoarkCats** [comment]
Yeah it seems to be the same, also side note: I'm on win 10, so happens on both 10 and 11

**Comment by misode** [comment]
I'm going to assume that this was the same issue as #1601
