### ISSUE TITLE
Subcommand "on" in "execute" do not show up

### ISSUE THREAD

**Issue by rcubedev** [SpyglassMC/Spyglass#1544]
![image](https://github.com/user-attachments/assets/dce242e9-f670-4314-beb7-3b823a5f9aed)

**Comment by Ellivers** [comment]
What's your pack format set to in your `pack.mcmeta`? `execute on` was added in 1.19.4, meaning the pack format should be 12 or higher.

**Comment by rcubedev** [comment]
Sorry- I hadn't realised that the data version was incorrect.

I'll close this issue.
