### ISSUE TITLE
Bug: Does not recognise "execute on"

### ISSUE THREAD

**Issue by KotiasFeet** [SpyglassMC/Spyglass#1545]
![image](https://github.com/user-attachments/assets/7eea2b00-d5d7-4ec3-b73c-c1119f1bbf79)
![image](https://github.com/user-attachments/assets/cca01d18-4d70-46e1-b403-88e1618c167e)

Can not write "execute on" commands. None of the existing "on" commands are getting recognised.

```execute on passengers run say hello
execute on attacker run say hello
execute on controller run say hello
execute on leasher run say hello
execute on origin run say hello
execute on owner run say hello
execute on vehicle run say hello
execute on target run say hello
```

**Comment by Nico314159** [comment]
What is your `pack_format` in the mc-meta file?
