### ISSUE TITLE
Spyglass incorrectly expects only string under "Instrument" components

### ISSUE THREAD

**Issue by witti-stack** [SpyglassMC/Spyglass#1550]
goat horns allow for more complex component fields that aren't just strings under the "instrument" component tag.
the code works when I run it in game, but is marked as incorrect by Spyglass.

![image](https://github.com/user-attachments/assets/188e93cc-d2a0-4396-a09d-c741c414c281)

**Comment by MulverineX** [comment]
Duplicate of https://github.com/SpyglassMC/vanilla-mcdoc/issues/14
