### ISSUE TITLE
Type specific advancements are missing some entities

### ISSUE THREAD

**Issue by shoberg44** [SpyglassMC/Spyglass#1560]
Missing some entities in type specific entity predicates in advancements such as boat, fox, horse, llama, mooshroom, parrot, rabbit, tropical fish, and villager.

I believe the wiki is incomplete.

![image](https://github.com/user-attachments/assets/a05933dc-9cbb-4b74-a114-bcc39a4d0185)

**Comment by MulverineX** [comment]
(On mobile rn, this issue should be transferred to vanilla-mcdoc)
