### ISSUE TITLE
I still get errors such as "Expected <criteria: objective_criteria>"

### ISSUE THREAD

**Issue by Ho9tocraft** [SpyglassMC/Spyglass#1561]
I am not sure if this is a language server side issue or a client side issue, but I still get "Expected <criteria: objective_criteria>" and "Trailing data encountered: " teamkill.red", etc., but I am still getting errors for team-related scoreboards. What is the reason for this?
If this is a fault on the spyglass side, please fix the bug ASAP.
In the meantime, I would like to thank you for this bug fix, as I do not see any other errors occurring for "teamkill.red" or other score conditions in other areas. Thank you very much.
However, since the error still occurs, please fix it ASAP and as soon as possible.

**Comment by misode** [comment]
@Ho9tocraft Could you provide the exact command that you're experiencing issues with, as well as a screenshot of the error?
