### ISSUE TITLE
"Open Cache Folder" fails when the mc-je cache is missing

### ISSUE THREAD

**Issue by Dahesor** [SpyglassMC/Spyglass#1563]
When I am trying to send the mc-je folder to someone cannot download from GitHub, we found out that if the download never started, the Cache folder will not be created, and the `Open Cache Folder` command has no response.

It should be opening the higher level folder, or create the Cache folder even if the downloads failed.

Thanks

**Comment by MulverineX** [comment]
The command should work in this scenario regardless of #1480
