### ISSUE TITLE
The Spyglass Language Server crashes

### ISSUE THREAD

**Issue by YocraftGG** [SpyglassMC/Spyglass#1569]
I am using is v4.2.0.

I get the error:
`The Spyglass Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

Here is the log:
[log.txt](https://github.com/user-attachments/files/16624522/log.txt)

**Comment by misode** [comment]
It looks like the extension is unable to download the necessary resources from `raw.githubusercontent.com`. Is this domain blocked in your country? Are you using a VPN or could you try using one? Is your network misconfigured in another way?

**Comment by Wortex02** [comment]
I'm having the same issue, but it seems to be resolved when I downgraded it to version 4.0.1

**Comment by misode** [comment]
@Wortex02 Could you share the language server log? Run the `Spyglass: Show Output` command.

**Comment by Wortex02** [comment]
@misode You mean this? [output.txt](https://github.com/user-attachments/files/17462986/output.txt)

**Comment by misode** [comment]
@Wortex02 Looking at that log, I do not see any signs of the language server crashing. If you experience a crash again, please create a new issue with the output log attached. Thanks!

**Comment by Wortex02** [comment]
@misode Oh, that was the log for the functioning version which is 4.0.1. I thought you wanted that one. I can give the crash log that I get in version 4.2.3 here: [output crash.txt](https://github.com/user-attachments/files/17465456/output.crash.txt)
