### ISSUE TITLE
Spyglass doesn't auto-complete nor validate data in compound form when specified in `execute if data`

### ISSUE THREAD

**Issue by Ellivers** [SpyglassMC/Spyglass#1571]
![image](https://github.com/user-attachments/assets/3b1b24bf-b901-4019-aa48-7fbda0e208d9)

![image](https://github.com/user-attachments/assets/1ae31ca1-204b-4973-9aea-e830e266f18f)

**Comment by NeunEinser** [comment]
Duplicate of #1365
