### ISSUE TITLE
Cannot find `pack.mcmeta` when projectRoot is "complex"

### ISSUE THREAD

**Issue by SPGoding** [SpyglassMC/Spyglass#1572]
Example project root that doesn't work: `file:///c%3A/Users/foo/AppData/Roaming/.minecraft/saves/%C2%A7a%C2%A7lVersion%201.21%20%C2%A74%C2%A7l%5B4.5%5D%C2%A77/datapacks/bar/`, which after percent decoding is `file:///c:/Users/foo/AppData/Roaming/.minecraft/saves/§a§lVersion 1.21 §4§l[4.5]§7/datapacks/bar/`

Maybe all those percent encoding messed something up?

**Comment by misode** [comment]
The issue seems to be caused by https://github.com/sindresorhus/globby/issues/81

I didn't immediately find a workaround. We should probably not use glob matching to walk the file tree.

**Comment by SPGoding** [comment]
I assume it should not be too difficult to implement a file tree walk ourselves
