### ISSUE TITLE
The Error "Expected Nothing Spyglassmc(1.20)"

### ISSUE THREAD

**Issue by BooleanTrueM** [SpyglassMC/Spyglass#1574]
I got the error like this.
<img width="289" alt="image" src="https://github.com/user-attachments/assets/b494278b-4149-43e0-b9b9-440615409f37">
It not only appears in pack.mcmeta, but also appears in load.mcfunction! And all json files in my datapack have no code hints!

I just created a file `spyglass.json` in my datapack folder, the content is:
>{
    "env": {
      "env": "jsDelivr"
    }
  }

And I modified the "hosts" file. But it still can't work!

 Is this a bug? Could someone tell me what should I do? Thanks!

**Comment by misode** [comment]
Could you run the `Spyglass: Show Output` command and share the log file?

**Comment by BooleanTrueM** [comment]
> Could you run the `Spyglass: Show Output` command and share the log file?

Here it is.
[log.txt](https://github.com/user-attachments/files/16648108/log.txt)

**Comment by misode** [comment]
It looks like the extension is unable to download the necessary resources from `api.github.com` and `raw.githubusercontent.com`. Are those domains blocked in your country? Are you using a VPN or could you try using one? Maybe your network is misconfigured in another way?

**Comment by BooleanTrueM** [comment]
> It looks like the extension is unable to download the necessary resources from `api.github.com` and `raw.githubusercontent.com`. Are those domains blocked in your country? Are you using a VPN or could you try using one? Maybe your network is misconfigured in another way?

It is solved now.
You're right, this is a network problem. The Github domains are blocked in my country. I modified all these domains in "hosts" file, and it can work.
In the end, Thanks for you help!
