### ISSUE TITLE
Pack format x does not match the actively loaded version y.

### ISSUE THREAD

**Issue by fullwoodenshovel** [SpyglassMC/Spyglass#1575]
I'm getting this error when making a new datapack:
![image](https://github.com/user-attachments/assets/0bf8be56-5f3b-496d-9b7f-3ca96f12f1e5)

Upon disabling and enabling the extension, it doesn't fix it. Upon restarting VSCode it doesn't fix it, and upon following the directions given in the details, it still doesnt fix it:
![image](https://github.com/user-attachments/assets/c11e323b-7f12-480e-b161-3659ee12e720)

This error means that the syntax is for 1.18.2 instead of 1.21.1, and I'm not sure what else I could try. Thanks.

**Comment by misode** [comment]
Do you have other `pack.mcmeta` files in your current workspace? Right now the extension is limited to loading a single version, and it tries to do that by finding the first `pack.mcmeta` files that it can find.

Otherwise, could you share the output log of the extension? You can get this by running the `Spyglass: Show Output` command.

**Comment by fullwoodenshovel** [comment]
Ah. I do have other `pack.mcmeta` files in my workspace...
Are the only ways to do that by either making the one datapack my whole workspace or using that manual method by making a new file?

**Comment by misode** [comment]
> Are the only ways to do that by either making the one datapack my whole workspace or using that manual method by making a new file?

@fullwoodenshovel A third option is using the global `Spyglass > Env > Game Version` vscode setting to `Latest Release`, which will match pack format 48 right now, but you're probably better off by creating a `spyglass.json` file if you want to open the entire workspace and load 1.21.1
