### ISSUE TITLE
Spyglass taking forever to Initialize usually 10 to 15 minutes....

### ISSUE THREAD

**Issue by ArsiTheFox** [SpyglassMC/Spyglass#1578]
Anytime I open VSCode the datapack snippet servers takes forever to load...
![nmTsYzev52](https://github.com/user-attachments/assets/a91b8e67-fe48-4f8d-9fb0-13b7e7399272)

This causes me not allowed to use the snippets until it finishes..... it has been maybe 6 min and it is still Initializing
![image](https://github.com/user-attachments/assets/9cc8fb8a-2b45-42f3-a118-bb6836b53fd5)

**Comment by ArsiTheFox** [comment]
It just finished loading... took around 13 min

**Comment by ArsiTheFox** [comment]
Shutting down and opening again

**Comment by misode** [comment]
Would you be able to share your workspace folder so we can try to reproduce the issue?

**Comment by B1BU** [comment]
I'm having the same issue, it's also making me unable to rename or move files

**Comment by misode** [comment]
@B1BU The second issue is #1414, see the top workaround in that issue. As for this issue, could you also share your workspace folder so we can investigate?

**Comment by ArsiTheFox** [comment]
Sadly no access to PC for a few days atm

**Comment by misode** [comment]
@ArsiTheFox @B1BU Is this still an issue? Are any of you able to share your workspace folder?

**Comment by ArsiTheFox** [comment]
@misode I am sorry, I found out it was because I had too much files in my workspace. I usually also have up all the default minecraft data and resource pack so I can reference in the workspace.....

**Comment by misode** [comment]
Ah good to know. Spyglass should autocomplete vanilla resource locations and you are able to ctrl+click on them to inspect them.

**Comment by TheAfroOfDoom** [comment]
@ArsiTheFox you may find these things helpful if you want to be able to access vanilla files without having them all downloaded in your actual workspace:

- https://kb.iu.edu/d/abbe (linux/macos only)
- https://code.visualstudio.com/docs/editor/multi-root-workspaces
