### ISSUE TITLE
"attributes" key in entity NBT being unknown

### ISSUE THREAD

**Issue by saladbowling** [SpyglassMC/Spyglass#1580]
I don't know if this has been reported yet. However, I came across this while developing.

I'm unsure if this was changed in 1.20.5 or 1.21, but the "Attribute" key was replaced by "attribute" in entity summon commands.

e.g. (previously) /summon zombie ~ ~ ~ {Attributes:[{Name:"minecraft:generic.max_health",Base:500}],Health:500f}

e.g. latest version /summon zombie ~ ~ ~ {attributes:[{id:"minecraft:generic.max_health",base:500}],Health:500f}

When typing the latest version command into Spyglass, it warns that "attribute" is an unknown key. It seems that the attribute NBT tree has not been updated yet.

I also can confirm my pack.mcmeta file is 48 for 1.21.

Correct Usage:
![image](https://github.com/user-attachments/assets/79ee150d-68a7-473a-b3f8-8628008a1c9b)

Incorrect Usage (from 1.20.4 and before and what Spyglass uses):
![image](https://github.com/user-attachments/assets/fa21194e-6072-487c-856a-68024f412c00)

Unknown key of "attribute" when you use it correctly:
![image](https://github.com/user-attachments/assets/48eee7f8-da04-4cae-a460-bb3e9eed658e)

A great extension! An excellent tool for mapmaking.

**Comment by Ellivers** [comment]
I can't reproduce this.

**Comment by MulverineX** [comment]
probably a cache issue, @saladbowling run the vscode command "Spyglass: Clear Project Cache"

**Comment by saladbowling** [comment]
Hi @MulverineX, that fixed it. I appreciate your help!
