### ISSUE TITLE
Validate pattern in shaped crafting recipes

### ISSUE THREAD

**Issue by Ellivers** [SpyglassMC/Spyglass#1581]
Each row in the `pattern` field must be of the same width.

`Parsing error loading recipe namespace:test
com.google.gson.JsonParseException: Invalid pattern: each row must be the same width`

**Comment by MulverineX** [comment]
Fixed by https://github.com/SpyglassMC/vanilla-mcdoc/commit/89813b60fdba20ae574ed1d24172f457b2274ac9
