### ISSUE TITLE
Suggestion: Support common stardard practices & add an option to reccomend them where possible

### ISSUE THREAD

**Issue by Bowswa** [SpyglassMC/Spyglass#1584]
I use 3 smithed standards, including the "pack ID" in the pack.mcmeta, which always throws me a warning. as someone who likes having no warnings, and is also incredibly annoyed everytime i look at a vanilla log and find those stupid missing sound warnings, i think that the extension should at least support common standard practices like this.

However, a further step could be taken, which would add an option to throw a warning when you forget to follow a standard you have enabled. So for example, if i forget to add that pack id if an update to pack.mcmeta is made and i use a generator to get the format down, i would have a warning telling me i forgot to add the ID.

**Comment by MulverineX** [comment]
#1208
