### ISSUE TITLE
single quotation mark with a \ before it in json text reported wrong errors

### ISSUE THREAD

**Issue by akastrmix** [SpyglassMC/Spyglass#1588]
![image](https://github.com/user-attachments/assets/3de3a2f8-f272-4c4f-ae5e-e9cbc8911d28)
Like shown in the screenshot. The command works perfectly in game.
```[tasklist]
### Tasks
```

**Comment by SPGoding** [comment]
I'm pretty certain it is not proper JSON to allow arbitrary characters to be escaped in strings. Minecraft might be parsing this in a lenient mode, which we don't support yet (see #1309).

![JSON string automation](https://www.json.org/img/string.png)
