### ISSUE TITLE
Enchantment explosion offset should be allowing floats

### ISSUE THREAD

**Issue by propfeds** [SpyglassMC/Spyglass#1595]
The code in this image should work in-game. However, it's marked as an error by Spyglass.
![image](https://github.com/user-attachments/assets/90aa1e5d-174d-4ef9-ac53-94f028828ef0)

The odd thing is that the wiki also states that they're ints, even though floats work.

**Comment by FracturedFlux** [comment]
encountered this exact problem while trying to code an enchantment called whirlpool

**Comment by propfeds** [comment]
> encountered this exact problem while trying to code an enchantment called whirlpool

that is some crazy luck that we had the same name idea then hmmmm

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/9c0d5a7323a284ce8085cbddec54194d094b0e22
