### ISSUE TITLE
"Expected a map-like" Error in Custom Enchantment List of Requirements

### ISSUE THREAD

**Issue by BenApe** [SpyglassMC/Spyglass#1596]
When listing multiple requirements for a custom enchantment, the "Expected a map-like" error appears. Minecraft allows the use of multiple requirements in a list, so this error should not appear.

![image](https://github.com/user-attachments/assets/24c2a5fe-ac2b-4383-80fb-354637f9852a)

I tested the above code and it works as intended.

**Comment by propfeds** [comment]
That's so handy. I've always used `all_of`, so this is much faster to write.
