### ISSUE TITLE
False error for resource pack format 34

### ISSUE THREAD

**Issue by XDFlame** [SpyglassMC/Spyglass#1597]
Resource pack format 34 encompasses releases 1.21 and 1.21.1, however spyglass falsely marks that it doesn't have any release versions
![image](https://github.com/user-attachments/assets/f9860071-faaa-4f2c-bf51-ec77cb94a520)

**Comment by Kesuaheli** [comment]
Resourcepacks arn't supported by spyglass yet. Spyglass thinks it is a `pack.mcmeta` of a datapack with version 34, which belongs to a snapshot (24w10a).
