### ISSUE TITLE
Show error instead of warning when an incorrect tag entry is present

### ISSUE THREAD

**Issue by Ellivers** [SpyglassMC/Spyglass#1600]
Currently, Spyglass shows a warning for nonexistent entries in tags, despite Minecraft showing an error for it and failing to load the tag.

![image](https://github.com/user-attachments/assets/d4fad9a5-2c8c-4d52-a404-03d26dc78a90)
![image](https://github.com/user-attachments/assets/483f2a86-cbcd-4e1e-aa2d-a9dba22c1c52)

This applies to all tags, not just function tags.

**Comment by misode** [comment]
I don't think we're going to change this. The `undeclaredSymbol` linting rule is a warning by default, mostly because it is not a syntax error and because there are some occations where this is not a problem (using a `#c:something` tag, referencing symbols from a dependency, other pack, or mod)

**Comment by misode** [comment]
@Ellivers I don't immediately see why tags should be handled differently. It is possible to manually configure this linting check to emit an error, see https://spyglassmc.com/user/lint/undeclaredSymbol
