### ISSUE TITLE
"Expected Nothing" in all JSON files and NBT tags

### ISSUE THREAD

**Issue by Lunaticol** [SpyglassMC/Spyglass#1609]
I keep getting "expected nothing" errors on all of my tags. from my knowledge these tags should be correct as they load perfectly fine in game. ![image](https://github.com/user-attachments/assets/b52ed6f1-5822-4f10-9409-9e92e6fff0ae)

**Comment by misode** [comment]
Could you run the `Spyglass: Show Output` command (after bringing up the command palette with Ctrl+Shift+P), and then share that log file here?

**Comment by Lunaticol** [comment]
https://mclo.gs/9ZkLyjP

**Comment by misode** [comment]
Can you try resetting your project cache? You can do this by running the `Spyglass: Reset Project Cache` command. You may need to reload vscode and/or close all opened files afterwards.

If this doesn't fix it, you can try the second option: Run the `Spyglass Open Cache Folder` command, close vscode, and then delete everything in the cache folder.

**Comment by Lunaticol** [comment]
Resetting and Clearing the cache did not work. it all just tells me the same error agian

**Comment by misode** [comment]
Do you only have this issue with tags? Or also with other json files or NBT in mcfunctions?

**Comment by Lunaticol** [comment]
I'm only seeing it effect my Functions and Tags
[Image](https://github.com/user-attachments/assets/d2996592-bbfb-47ea-b873-13ae3c641854)

**Comment by Lunaticol** [comment]
effects advancements to
![Image](https://github.com/user-attachments/assets/8650d273-c064-487d-beb9-91de39f43065)

**Comment by Lunaticol** [comment]
affects recipes to ![Image](https://github.com/user-attachments/assets/8f3db646-8126-4c26-9889-6ce35b465248)

**Comment by Tschipcraft** [comment]
Happened to me as well, but only on one project I'm working on. Resetting the cache did not work.
Affects tags, advancements, pack.mcmeta, json after tellraw and NBT in mcfunction. External json files are unaffected.
My log: https://mclo.gs/VYTd5uV

**Comment by Lunaticol** [comment]
[log.txt](https://github.com/user-attachments/files/17883066/log.txt)
The odd thing is that it works fine in other datapacks??? Ive even moved everything out of the specific datapack it was bugging in and the copied folders work just fine outside of the datapack I'm working on. I have even deleted the entire thing and re-copied it from github and still get errors.

**Comment by Tschipcraft** [comment]
I tried, but same problems. My log: https://mclo.gs/7bZQUEa
Maybe it's reproducible? You could try cloning https://github.com/sa-shiro/spawnanimations/tree/1.20.5 and test on your end

**Comment by misode** [comment]
Were both of those logs from the first restart after following all those steps? Because I still see `Skipped thanks to valid cache in memory` logs which indicate that the extension is reusing some possibly old state.

**Comment by Tschipcraft** [comment]
Yeah, I saw those in mine too. I had to restart VS Code for the extension to fully load after reinstalling. I could do it again and get the log right after if that's helpful

**Comment by Lunaticol** [comment]
Same with above

**Comment by Plagiatus** [comment]
For me it depends on how I open the datapack. If I open it 

a) directly or
b) through the folder directly above (e.g. the `datapacks` folder of a world)

the datapack(s) and spyglass load fine for me.

However, when I open the world folder with the `datapacks` folder inside of that, that's when I see this issue.

-----

For me all JSON files (advancements, recipes, item modifiers, loot tables, tags) are affected.

As for commands, it seems that only those that include NBT data (summon, data, execute store storage), item components (item replace) or JSON text (title, tellraw) are affected by this issue. (not macro lines)

-----

Another issue that seems to come in tandem with this (as it's not there if the folder is loaded directly as described above), is that all my functions are unrecognized and thus a warning is shown: `cannot find function foo:bar (rule: undeclaredSymbol)`. I assume this is considered a separate issue, but I noticed it seems to coincide with this issue.

**Comment by misode** [comment]
@Lunaticol @Tschipcraft @Plagiatus I have added some debug log messages in `v4.4.1`. It would be really helpful to get logs after you:
1. Make sure the vscode extension is updated to the latest version
2. Open the cache folder and close vscode completely
3. Wipe the entire cache folder (`downloader` and `symbols`)
4. Reopen vscode in your project and give it time to initialize
5. Immediately share the log here, without reloading or resetting the project cache

**Comment by Lunaticol** [comment]
https://mclo.gs/z1LrOiT

I noticed while trying to get the logs that it'll only start sprouting errors whenever  "Received notification 'textDocument/publishDiagnostics' " appeared.

**Comment by misode** [comment]
Thank you. Unfortunately (or fortunately), the issue wasn't caught by the new debugs. At least I can verify that the mcdoc archive is successfully downloaded and its content is complete. I will have to add some more debug messages.

**Comment by Tschipcraft** [comment]
https://mclo.gs/uH7OT9u

**Comment by misode** [comment]
Okay I got another version adding some more debug logs.

Rename this file to `.vsix` and then run `Extensions: Install from VSIX...`
[datapack-language-server-4.4.2-beta.1.zip](https://github.com/user-attachments/files/18264593/datapack-language-server-4.4.2-beta.1.zip)

Like earlier, make sure the cache is completely clear. Thanks again for all your participation while trying to figure this out!

**Comment by Tschipcraft** [comment]
https://mclo.gs/dZGhG2c

**Comment by misode** [comment]
Eureka! @Tschipcraft Could you share the contents of your `.gitignore` file?

The "files to bind" summary should also be listing `mcdoc` files and all files in the vanilla data pack and resource pack, and it doesn't in your log. The problematic log is
```
[Project#getTrackedFiles] Listed 16950 supported files
[Project#getTrackedFiles] After ignoring, keeping 237 tracked files
```
The problem here is that the exclude config is also applying to the dependency files, not only to the project files.

When you've shared the gitignore, can you try setting the following `spyglass.json` config? Until there is a fix, I think this should be a workaround.
```json
{
  "env": {
    "exclude": []
  }
}
```

**Comment by Plagiatus** [comment]
(I am not the provider of the above logs but) that sounds about right. My gitignore is this: https://github.com/Plagiatus/MapmakingTemplate/blob/main/.gitignore

It ignores everything except a few select folders, because I load my entire world into the git and only push relevant files.

**Comment by Lunaticol** [comment]
I can confirm adding the code below to your `spyglass.json` does indeed fix the issue.
```JSON
{
  "env": {
    "exclude": []
  }
}
```

For anyone else who might be confused on how to do this, just create a [`spyglass.json`](https://github.com/user-attachments/files/18266736/spyglass.json) file like you would `pack.mcmeta` and add the code above, or just drop the linked file directly into it.

Should look like this
![Image](https://github.com/user-attachments/assets/7f091f41-92c7-4da3-9a7f-73a737931879)

To answer the question above, this is my .gitignore file: https://github.com/Lunaticol/Lunas-Origins/blob/main/.gitignore

**Comment by Tschipcraft** [comment]
Same here, the .gitignore if still needed: https://github.com/Tschipcraft/spawnanimations/blob/v1.10/.gitignore
