### ISSUE TITLE
Trusted Entity Data not known (1.21.1)

### ISSUE THREAD

**Issue by jerjerje** [SpyglassMC/Spyglass#1612]
The `Trusted` Entity Data is not known to Spyglass. Instead, it wants to use `TrustedUUIDs`. This is not used in the game anymore. Further Information: on the [minecraft wiki](https://minecraft.wiki/w/Fox#Entity_data) (Note: The Wikis Changelog does not list when it was changed to `Trusted`, so I don't know what minecraft versions this affects).

Test inside Minecraft 1.21.1:
Using the `data get entity` command any nearby fox, you can see, that it shows the `Trusted` Field not `TrustedUUIDs`. On a random fox, it should be an empty list. If two foxes are bred with sweet berries, the child will have the player in its `Trusted` tag.

Steps to Replicate in Spyglass:
1. Write this command `execute if data entity @n[type=fox] Trusted[0]` into a mcfunction file.
    Spyglass will show the error message: `Unknown Key "Trusted" spyglassmc(1.21.1)`

2. Create an item modifier file.
    Paste the following data in it:
```
[
  {
    "function": "minecraft:set_components",
    "components": {
      "minecraft:entity_data": {
        "id": "minecraft:fox",
        "Trusted": []
      }
    }
  }
]
```
  Spyglass will show the error message: `Unknown Key "Trusted" spyglassmc(1.21.1)`
  The Autocomplete will also suggest `TrustedUUIDs` instead of `Trusted`.

**Comment by misode** [comment]
Thanks for the report! This has been fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/e2c908b4b38956338cfab536ad477e6b67f8fa62, reloading vscode should fix it for you
