### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1621]
> @misode Oh, that was the log for the functioning version which is 4.0.1. I thought you wanted that one. I can give the crash log that I get in version 4.2.3 here: [output crash.txt](https://github.com/user-attachments/files/17465456/output.crash.txt) 

 _Originally posted by @Wortex02 in [#1569](https://github.com/SpyglassMC/Spyglass/issues/1569#issuecomment-2427431616)_

**Comment by misode** [comment]
@Wortex02 Do you have a custom `spyglass.json` config, or have you modified the `spyglass.env.gameVersion` vscode setting?

**Comment by cootshk** [comment]
I'm having the same issue. I don't have a `spyglass.json` or `spyglass.env.gameVersion` setting
