### ISSUE TITLE
Duplicated dispatcher case Warning

### ISSUE THREAD

**Issue by Ho9tocraft** [SpyglassMC/Spyglass#1631]
I have not been directly affected yet, but this error message bothered me so much that I had to raise the issue.
I am assuming it is an error around mcdoc, but there are 19 “Duplicated dispatcher case” warnings from memory.mcdoc and I would like to know what this is and if it is possible for the user to take care of it.
If this is something that cannot be handled by the user and needs to be handled by the developer, please respond and reflect this as soon as possible.
I encountered this warning in the Minecraft 1.20.6 datapack environment.

**Comment by misode** [comment]
Could you try running the `Spyglass: Reset Project Cache` command?

**Comment by Ho9tocraft** [comment]
Thank you. All warnings are fixed.
