### ISSUE TITLE
Weird Error highlighting when no error is present

### ISSUE THREAD

**Issue by NeleIsDead** [SpyglassMC/Spyglass#1636]
Found some syntax errors that work fine but get highlighted for some reason
![Image](https://github.com/user-attachments/assets/b0831916-273f-4425-a3a1-247566e42088)
![Image](https://github.com/user-attachments/assets/fc1500bc-a23e-42c3-9969-e44c496d9083)

EDIT: please ignore my terrible naming

**Comment by NeunEinser** [comment]
For the first one, resource locations cannot contain uppercase.

**Comment by NeleIsDead** [comment]
They can. The loottable worked completely as intented
