### ISSUE TITLE
Delete & Rename actions sometime "corrupted" on VSCode when using Spyglass

### ISSUE THREAD

**Issue by KawaMood** [SpyglassMC/Spyglass#1652]
## The issue(s)

I don't know how to technically explain it, but Spyglass seems to "corrupt" VSCode actions in data packs projects.

Basically when I try to delete a folder, it shows me a toast saying it requires to perform the action as an administrator (_so already here it is not normal_) and then when I do it, it shows an error : "Failed to delete using the Recycle Bin" and asks me if I want to delete it permanently instead.

This video shows the issue: https://streamable.com/i9pdgb
1. Trying to delete a folder shows the error I mentioned above.
2. After disabling the Spyglass extension and restarting VSCode, it works fine.
3. After re-enabling Spyglass, the same issue start to happen again.

Relatively, this kind of issues happens when I try to rename a file (this video has been recorded on another laptop) : https://streamable.com/ljez2q
While having Spyglass extension enabled, trying to rename a file just make VSCode just "load" in loop and eventually stop to work. I need to restart it completely. The name is changed afterwards, so I presume the "Rename" action manages to pass when the extension isn't active due to initializing or exiting the app.

## How to reproduce

I tried some things to force a folder to become problematic, unfortunately, I have no idea how to reproduce. I don't have this issue on half on my data packs in the exact same project, and have it on the other half, it randomly begin to happen in any folder with time. All folders and files have the same permissions (total control by system). 
I tried to clear Spyglass' cache and also completely delete all cache folders of VSCode, but it still happens.
Another data packer (_RedCoal_) said he encountered the exact same issue, so it doesn't sound to be relative to me specifically.

**Comment by misode** [comment]
I believe this is the same issue as #1414
