### ISSUE TITLE
The Spyglass Language Server Crashed Again and Again

### ISSUE THREAD

**Issue by LittleLambMero** [SpyglassMC/Spyglass#1659]
When I update to version higher than "4.2.0" (include), VS Code will catch the error "The Spyglass Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." But if I changed the version lower than "4.1.2" (include), this problem will disappear.
What does this happen? And what can I do to fix the problem?

I also provide the log when the error occurs as shown in the attachment.
[4.2.0 console log.txt](https://github.com/user-attachments/files/17962706/4.2.0.console.log.txt)
[4.3.1 console log.txt](https://github.com/user-attachments/files/17962707/4.3.1.console.log.txt)

**Comment by Dahesor** [comment]
Looks like a very typical internet issue to me.
If you are in China, check out this: https://www.bilibili.com/video/BV1XJhKeGEm7/
This is a tutorial on changing your DNS so you can connect to GitHub properly

**Comment by LittleLambMero** [comment]
> Looks like a very typical internet issue to me, a lot of people have faced this. If you are in China, check out this: https://www.bilibili.com/video/BV1XJhKeGEm7/ This is a tutorial on changing your DNS so you can connect to GitHub properly

But I'm in Taiwan, the solution is also the same?

**Comment by Dahesor** [comment]
You can try at least

**Comment by LittleLambMero** [comment]
OK then I'll give it a try these days.

Dahesor ***@***.***> 於 2024年12月5日 週四 上午3:27寫道：

> You can try at least
>

**Comment by misode** [comment]
Looking at the original log, I actually believe this is a duplicate of #1621

**Comment by LittleLambMero** [comment]
Ok I try the solution by the tutorial video on BiliBili, then it did! Thanks for your help!!
