### ISSUE TITLE
Doesn't recognise player data "SpawnAngle" key

### ISSUE THREAD

**Issue by mePenguh** [SpyglassMC/Spyglass#1660]
Spyglass doesn't recognise the player data `SpawnAngle` key

![Image](https://github.com/user-attachments/assets/8233e7a5-5dc0-4042-b23b-8a649e768fb6)
![Image](https://github.com/user-attachments/assets/a85fee88-d266-4eec-9a24-adc2675bf666)

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/21703dd46bb0f3406da77aef9ac728605ea1169d
