### ISSUE TITLE
Unknow key "components"

### ISSUE THREAD

**Issue by AmadeuszSosna** [SpyglassMC/Spyglass#1661]
spyglass tells that componens is unknow key![Image](https://github.com/user-attachments/assets/246e56b9-125a-4b40-b22c-d1d73b8ff049)

**Comment by Sul4urx** [comment]
Check what version of Spyglas you ar using.

**Comment by Sul4urx** [comment]
Chek what version of Spyglas you ar using

**Comment by Sul4urx** [comment]
Check what version of Spyglass you are using.

**Comment by misode** [comment]
@AmadeuszSosna Could you check whether you have the right `pack_format` set? (41 or higher if you're using item components)

If that is already the case, make sure that you've reloaded vscode, given the language server enough time to initialize, and if necessary close and reopen active tabs.

If it is still showing incorrect warnings, try running the `Spyglass: Reset Project Cache` command.
