### ISSUE TITLE
Lava falling property key not recognized

### ISSUE THREAD

**Issue by BemusedLeader10** [SpyglassMC/Spyglass#1662]
The falling property key is used for lava springs, yet in the most recent update this is now no longer recognized by Spyglass

```
"state": {
  "Name": "minecraft:lava",
  "Properties": {
    "falling": "true"
  }
}
```

![Image](https://github.com/user-attachments/assets/48b98822-3dfb-40a3-9bb3-b7a141e654ca)

**Comment by misode** [comment]
As far as I can tell, `falling` is not a block property of lava (it is a fluid property though). You cannot autocomplete it in `/setblock` and it isn't present in the data generated files.

**Comment by misode** [comment]
Okay I see. The issue is actually that the `spring` feature type uses a fluid state rather than a block state.
