### ISSUE TITLE
"color" key is unrecognized in worldgen/biome particles

### ISSUE THREAD

**Issue by BemusedLeader10** [SpyglassMC/Spyglass#1679]
See title![Image](https://github.com/user-attachments/assets/03d63b61-e9fd-4ce7-ac7c-4c27355cb8f9)

**Comment by misode** [comment]
What is the particle type what you are using? It is covered by the error message.

**Comment by BemusedLeader10** [comment]
Sorry about that 😅
I was using minecraft:entity_effect
