### ISSUE TITLE
Ability to 'teach' linter which scoreboard objectives, teams, etc. exist without init file

### ISSUE THREAD

**Issue by TheMuffinPony** [SpyglassMC/Spyglass#1683]
Hello!  I have a project with hundreds of scoreboard objectives, teams, etc.  A problem I have with Spyglass is that it marks every bossbar, objective, and team as being unknown.

Example:
```
Cannot find objective “tmp” (rule: undeclaredSymbol) spyglassmc(1.21.4)
```

The datapack I'm using was specifically made to augment a world (rather than being available to add to any world), so I wish I could tell the linter "here's a list of valid scoreboard objectives, teams, etc." without having to make an init file that contains every objective - i.e. in my `.spyglassrc.json` file.

I further wish it could be added in VS Code's "quick fix" list to say "I am aware that this objective exists, but it was created manually" and optionally tell it what kind of objective it is (dummy, trigger, dead bushes picked up, etc.)

**Comment by misode** [comment]
We're probably not going to add this.

> I wish I could tell the linter "here's a list of valid scoreboard objectives, teams, etc." without having to make an init file that contains every objective - i.e. in my .spyglassrc.json file.

This config or declaration file would be practically identical to an `init.mcfunction` file. So why don't you just create an mcfunction file that declares add objectives?

**Comment by NeunEinser** [comment]
You can hack this by changing the undeclared symbol rule to ignore scoreboard objectives, and add a lint ruke for "nameOfObjective". This lint rule is a regex which is meant to be used for a naming convention, but there is nothing stopping you from doing sth silly like `^objName1|objName2|objName3$`.

This might be hard to maintain for you, and I would also recommend an init function as the better alternative. You don't have to call that function either, if that doesn't work in your project.
