### ISSUE TITLE
score-holders that start with '*' are parsed incorrectly

### ISSUE THREAD

**Issue by rtaylor034** [SpyglassMC/Spyglass#1690]
score-holders that start with `*` are parsed as though there is a space between the `*` and the rest of the name. (ex: `*foo` is parsed as `* foo`)

This usually causes all further text in the line to show up as invalid, even though it is valid.
![Image](https://github.com/user-attachments/assets/c3491900-ffca-4171-a71c-114306d2c735)

**Comment by NeunEinser** [comment]
Possibly caused by #1644 (Fix for #1616)

**Comment by rtaylor034** [comment]
Def caused by #1644, evident by [this comment](https://github.com/SpyglassMC/Spyglass/pull/1644/commits/454fc0dce3ff5d3e9a5ea618ab4e6037e6934e55#diff-7987f65ce930aad2c2d44bb9dcb0ef6cc1d466f50873422daf1cfe15e6eeb99fR1358).
