### ISSUE TITLE
Auto completion adjustment

### ISSUE THREAD

**Issue by mathaym25** [SPYGlassMC/SPYGlass#383]
In auto completion of `/function`, currently it is like this:
`/function <namespace>:<foo>/<bar>`, which requires us to manually enter the `:` and `/`
If possible, it would be more convenient to have auto completion like this:
`/function <namespace:><foo/><bar>`, so that the `:` and `/` are directly proposed when we autocomplete a namespace or a folder.

In addition, autocompletion is missing for the advancement criteria (the last optional argument of the command `/advancement`), if it is possible to do so.

For the particle `dust`, it might be more suitable (if possible), to have `/particle dust <rgb> <size> <xyz> ...` instead of `/particle <name> <xyz>` with name which supports dust and rgb/size.

In the auto completion of blockdata and selectors, it would be more practical if auto completion completes, in addition to the argument, the `=` which follows, and why not the `{}` if necessary (for nbt and scores)
For example, in a selector, autocomplete `scores={}` instead of `scores`.
Or in blockdata, autocomplete `facing=` instead of `facing`

**Comment by SPGoding** [comment]
❌ The thing is that it's impossible to provide completions right after giving a completion ;(

So after you select `namespace:`, for example, there won't be completions for `foo/`. You have to trigger it by pressing Ctrl + Space manually, which imo is more complicated than just selecting `namespace` and typing `:`.

✔️ Yes, we will provide completions for advancement criteria.

❌ The `dust <rgb>` part is counted as `<name>` in game, so I want to keep consistent with the game.

✔️ Yes, completing `scores={}` is better than `scores`. This can also apply to NBT compounds, lists, and arrays.

Also plz open individual issue for each suggestion in the future, thx a lot <3

**Comment by pca006132** [comment]
For `scores={}`, I think you can provide it as a snippet, which you can define the placeholder position.
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax

```ts
export namespace InsertTextFormat {
        // ...
	/**
	 * The primary text to be inserted is treated as a snippet.
	 *
	 * A snippet can define tab stops and placeholders with `$1`, `$2`
	 * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
	 * the end of the snippet. Placeholders with equal identifiers are linked,
	 * that is typing in one will update others too.
	 */
	export const Snippet = 2;
}
```
And I'm not sure if providing the `textEdit` field to append the namespace together with a `:` character could trigger completion again, maybe you can try it.
```ts
export interface CompletionItem {
        // ...
	/**
	 * An edit which is applied to a document when selecting this completion. When an edit is provided the value of
	 * `insertText` is ignored.
	 *
	 * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
	 * has been requested.
	 */
	textEdit?: TextEdit;
        // ...
}
```

**Comment by SPGoding** [comment]
Split into #835 and #836.
