### ISSUE TITLE
Colorful preview for text components

### ISSUE THREAD

**Issue by SPGoding** [SPYGlassMC/SPYGlass#396]
[Discord message](https://discordapp.com/channels/154777837382008833/259800273445191690/688810769080647690) inspired by MulverineX#???? and Boomber#????.

I guess we have to use the hacky [webview API](https://code.visualstudio.com/api/extension-guides/webview). More on this later.

**Comment by oOBoomberOo** [comment]
This would actually be possible with VS Code's semantics highlighting now, isn't it?

**Comment by SPGoding** [comment]
Merging into #735. Ideally the new integrated graphic JSON generator could preview text components.
