### ISSUE TITLE
Invalid THIS is displayed for completion of loot and recipes in rewards of advancements

### ISSUE THREAD

**Issue by ChenCMD** [SPYGlassMC/SPYGlass#599]
![image](https://user-images.githubusercontent.com/46134240/87876472-3d4f0680-ca13-11ea-9f96-9fd4f4b65d27.png)

![image](https://user-images.githubusercontent.com/46134240/87876467-345e3500-ca13-11ea-950d-24b5521d0393.png)

**Comment by SPGoding** [comment]
Sometimes people use the same names for relevant advancements/functions/loot tables/recipes, so this is the intended behavior that `THIS` will be provided for all these types.

**Comment by ChenCMD** [comment]
This should be an implementation that displays THIS if it exists

**Comment by SPGoding** [comment]
The user might use THIS and then trigger the quick fix to create that file though

**Comment by ChenCMD** [comment]
Well, that's right, I will close this issue.
