### ISSUE TITLE
Language server randomly freezes when editing

### ISSUE THREAD

**Issue by oOBoomberOo** [SPYGlassMC/SPYGlass#640]
This bug occurred very randomly, I haven't pinned it down yet but this usually happens when you try to edit command that has already been typed out to the end.

Re-doing the same action *doesn't* reproduce the bug as well so this is going to take some time to figure out.

Also, a side-effect of this is that I can no longer press [Spacebar] to add whitespace I **have** to press Shift + [Spacebar].

**Comment by SPGoding** [comment]
Please tell me if you're still encountering this in **3.0.0**

**Comment by oOBoomberOo** [comment]
The bug is unpredictable so I'll keep using it for a week first and then report back.

**Comment by oOBoomberOo** [comment]
No problem so far, this should be fine now.

**Comment by oOBoomberOo** [comment]
Nope, the bug is still there.
![](https://i.imgur.com/n4cq5pX.png)

**Comment by SPGoding** [comment]
Closing as I do not have enough information to reproduce this issue and the language server is under complete rewrite.
