### ISSUE TITLE
Add support for asset JSONs

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#658]
It would be nice if dh+ could also support assets alongside with data.

In datapacks, assets are often referenced, for example sound events that can be played using /playsound, fonts that can be used in text components, or language strings in text components or advancements.

Because of this, it already makes sense to develop a data/resource pack hybrid in the same workspace.
Personally, I actually have assets and data in the same directory (and git repo), and use file system links in Minecraft's resourcepack and datapack directories to point to that folder.

It would be nice to get support for both from the same extension so that it's possible to receive support for custom assets in the datapack part.

**Comment by SPGoding** [comment]
_Oh no I don't want to rename the extension_

**Comment by MulverineX** [comment]
This should be in milestone 4.2.0
