### ISSUE TITLE
CreateFile command is provided for quickfix even for functions whose access is prohibited by access modifier

### ISSUE THREAD

**Issue by ChenCMD** [SPYGlassMC/SPYGlass#684]
![image](https://user-images.githubusercontent.com/46134240/90973053-6b1af400-e559-11ea-95b7-d142dc77fab2.png)

**Comment by SPGoding** [comment]
> I find it difficult to understand the warning thrown when writing a functionPath that cannot be accessed due to access modifiers.
How about throwing another warning only in that case?

Relates to [this](https://discordapp.com/channels/666020457568403505/666020458453270535/746987792772497468).

**Comment by SPGoding** [comment]
Due to performance reasons, private resources are completely invisible in other functions. I don't think there's a good way to fix this ;/
