### ISSUE TITLE
IMP-Doc function definition quick fix

### ISSUE THREAD

**Issue by Neminite** [SpyglassMC/Spyglass#708]
The error checker already knows what should be in the file header. Could you add a quick fix option to automatically fix the error?
![image](https://user-images.githubusercontent.com/20189468/95381216-70d05d00-08ad-11eb-939f-865672d782b8.png)

**Comment by misode** [comment]
No longer relevant now that IMP-doc doesn't exist in v4 and we don't have a new spec yet
