### ISSUE TITLE
Switching the language mode from mcfunction to json results in errors

### ISSUE THREAD

**Issue by misode** [SPYGlassMC/SPYGlass#759]
### How to reproduce
1. Open a new document (`Ctrl+N`)
2. Write some small dummy json, for example `{"hello": "world"}`
3. Switch language mode to `mcfunction`
4. Switch language mode to `JSON`
5. There are errors `Invalid argument type . datapack`

**Comment by SPGoding** [comment]
Cannot reproduce in v4.
