### ISSUE TITLE
Renaming a folder when VSCode is open fails due to file lock on Windows

### ISSUE THREAD

**Issue by SirWindfield** [SPYGlassMC/SPYGlass#764]
To give some more context: I have a folder that contains all my datapacks that I work on as well as a template that I just copy paste to create a new datapack.
After copy pasting the template folder, I cannot rename the folder when VSCode is still open. It only happens when this plugin is installed. The only reason I can think of is that the language server does lock the files and renaming them doesn't work in that case on Windows, as access has been declared as exclusive.

Not sure what additional information I should submit here, so I just append the usual stuff:

__VSCode:__ 1.51.1 (user setup)
__OS:__ Windows_NT x64 10.0.19042
__Plugin:__ 3.1.1

**Comment by SPGoding** [comment]
Not sure why that's happening :eyes:

Theoretically the language server only reads file once when necessary, and should not lock the files in any situations.
