### ISSUE TITLE
Autocompleting JSON doesn't respect indentation preference

### ISSUE THREAD

**Issue by misode** [SPYGlassMC/SPYGlass#767]
This happens when you autocomplete a JSON list or object that has a default.

![image](https://user-images.githubusercontent.com/17352009/100116718-5c9fe980-2e74-11eb-9b77-9c51e7c4499c.png)
![image](https://user-images.githubusercontent.com/17352009/100116596-37ab7680-2e74-11eb-88dd-742d108f37a2.png)

**Comment by SPGoding** [comment]
Just a note: the [`formatting` request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_formatting) comes with a parameter of `FormattingOptions`, so we can definitely use that.
