### ISSUE TITLE
Duplicate single-use selector arguments don't result in an error

### ISSUE THREAD

**Issue by barraIhsan** [SPYGlassMC/SPYGlass#785]
Try write this `execute as @a[scores={test=1},scores={test_two=2},] run say test` and it didn't show up an error. Also you can autocomplete it
![image](https://user-images.githubusercontent.com/57800056/100844416-6cd84a00-34ae-11eb-913e-ecffc22f45da.png)

**Comment by MulverineX** [comment]
Updated title as this is also the case for other single-use arguments such as `type` and `distance`
