### ISSUE TITLE
No error in advancement selector

### ISSUE THREAD

**Issue by barraIhsan** [SPYGlassMC/SPYGlass#789]
Type `tellraw @a[advancements={nether/all_effect}] "Test"` it doesnt show up error!
![image](https://user-images.githubusercontent.com/57800056/101237817-56c8c480-370e-11eb-9486-09a68851d0ba.png)
But in Minecraft, its resulting error
![image](https://user-images.githubusercontent.com/57800056/101237839-7d86fb00-370e-11eb-8cd6-66606b638106.png)

The correct syntax : `tellraw @a[advancements={nether/all_effect=<true/false>}] "Test"`

**Comment by SPGoding** [comment]
Duplicate of #771
