### ISSUE TITLE
Custom regex conventions do not consider the entire string, resulting in confusing behavior

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/SPYGlass#792]
Example:
```json
{
	"datapack.lint.nameOfScoreHolders": ["warning", "/(?:0|-?[1-9][0-9]*)/"]
}
```
This will allow:
- 0 (intended)
- 1 (intended)
- 01 (not intended)

01 is allowed because both of the substrings "0" and "1" pass the test. I would have expected it to validate against the entire string as a whole, though.
Defining the convention as `/^(?:0|-?[1-9][0-9]*)$/` fixes the issue.

In case, ts does not support checking if the entire string matches as a whole, maybe it would make sense to not allow a regex component like that as a string, but instead always require the object definition, with a new regex field. That way the enclosing forward slashes could be dropped and added by the extension, as well as the `^` and `$`.

**Comment by ChenCMD** [comment]
This is the behavior intended, personally, but ... I don't know which one is actually better:man_shrugging:

**Comment by NeunEinser** [comment]
I don't see any benifit in the current behavior.
If one would actually take advantage of this, the regular expression would be extremely confusing and hard to understand, similarily bad as things like self-modifying code.
