### ISSUE TITLE
NBT path parser is not lenient with keys

### ISSUE THREAD

**Issue by Arcensoth** [SPYGlassMC/SPYGlass#800]
In the game, some characters that would be invalid when unquoted as SNBT keys (such as `*`, `+` and `@`) are nonetheless valid in NBT paths:

![image](https://user-images.githubusercontent.com/1885643/101860493-ee2d7d80-3b3b-11eb-997c-6e4386ecc8bc.png)

![image](https://user-images.githubusercontent.com/1885643/101860681-52e8d800-3b3c-11eb-9bac-d3890ebea5ad.png)

These characters are not handled the same way by DHP:

![image](https://user-images.githubusercontent.com/1885643/101860463-df46cb00-3b3b-11eb-82f2-62497fcdbd08.png)

```mcfunction
data modify storage foo:a * set from storage foo:b *
```

---

The current work-around for DHP is to just quote the keys in the NBT path::

![image](https://user-images.githubusercontent.com/1885643/101861075-38632e80-3b3d-11eb-863c-458a33c1372f.png)

```mcfunction
data modify storage foo:a "*" set from storage foo:b "*"
```

**Comment by SPGoding** [comment]
I wish I could just mark this as won't fix...

**Comment by Arcensoth** [comment]
This is a shot in the dark, but: is the solution possibly to add a new method like `StringReader.canInNbtPathKey()` instead of using `StringReader.canInUnquotedString()`?

https://github.com/SPYGlassMC/SPYGlass/blob/7c94c470262a42c1b2c63a63bc90279972114fe0/packages/datapack-language-server/src/parsers/NbtPathArgumentParser.ts#L139-L141

https://github.com/SPYGlassMC/SPYGlass/blob/7c94c470262a42c1b2c63a63bc90279972114fe0/packages/datapack-language-server/src/utils/StringReader.ts#L394-L396

**Comment by SPGoding** [comment]
Yes, that's the perfect solution for now. However I'm actually having a huge refactor going on, and I don't think that piece of code will even exist after the refactor ;D

**Comment by SPGoding** [comment]
Seems like [any characters](https://discord.com/channels/666020457568403505/746376708374134894/801666746137182208) (except space?) can be included in NBT path keys 🤔
