### ISSUE TITLE
Comments are not colored as such

### ISSUE THREAD

**Issue by nailuj29gaming** [SPYGlassMC/SPYGlass#808]
When I create a comment in my code, it does not color it like it does every other language.
mcfunction file: 
![image](https://user-images.githubusercontent.com/54189157/103594482-cde8a880-4ec6-11eb-8607-8ef5dfbdc3c4.png)
js file:
![image](https://user-images.githubusercontent.com/54189157/103594505-dd67f180-4ec6-11eb-8a43-b44d12967e86.png)

**Comment by SPGoding** [comment]
The re-written language server will color comments correctly.
