### ISSUE TITLE
How to disable yellow error highlighting

### ISSUE THREAD

**Issue by Bigious** [SPYGlassMC/SPYGlass#809]
Forgive me if I sound like a noob but I am new to the data pack creation scene. When using your extension and writing long summon commands that go a bit long it highlights the file as yellow even though the command works perfectly in-game, is there a way to remove this feature. While it's not the biggest deal in the world I can just be annoying sometimes. example below
![image](https://user-images.githubusercontent.com/48578318/104676969-5b818080-569d-11eb-98de-d491504dc645.png)

**Comment by NeunEinser** [comment]
What is an example of a command that causes that?

**Comment by SPGoding** [comment]
Could you please check the content of that file to see if there is any warnings (yellow underline) shown in it? I might be able to fix those issues in the future if they're false positives.

And speaking of the file names being highlighted, you could disable them in VS Code's `explorer.decorations.colors` setting.

**Comment by Bigious** [comment]
Okay here is a screenshot of the command that causes this problem. Once I delete the command the files return to normal or if I shorten the command by removing some of the extra modifiers. 
![image](https://user-images.githubusercontent.com/48578318/104812386-a347fb00-57b6-11eb-90f9-8f859389607c.png)

**Comment by Bigious** [comment]
Also after applying the recommended fix the line it still leaves the files highlighted yellow.

**Comment by NeunEinser** [comment]
`Team` is an nbt tag that only exists for living entities. That's why it's marked by the extension, since you are trying to set a tag which doesn't exist and thus doesn't have any effect.

There should be an option to disable it, however the wiki doesn't seem to mention anything.
@SPGoding I would have expected something like `datapack.lint.strictNbtTagCheck`, does that not exist?

**Comment by SPGoding** [comment]
Sadly, I don't think that's a thing yet ;(

**Comment by NeunEinser** [comment]
I went by the wiki which lists it as "tags common to all living entities" and there is no mention of it for falling sand entities.

**Comment by Bigious** [comment]
OMG sorry for wasting ur time I guess its just a problem with mcstacker

**Comment by SPGoding** [comment]
I just tested and seems like `Team` isn't a thing for falling blocks, so there's no issue here. 

Don't worry about this; good to know I have one less bug to fix ;D
