### ISSUE TITLE
Unnamed JSON files are unsupported

### ISSUE THREAD

**Issue by ChenCMD** [SPYGlassMC/SPYGlass#811]
![image](https://user-images.githubusercontent.com/46134240/104846701-3439e600-591f-11eb-8968-3edb6840c8ca.png)

**Comment by SPGoding** [comment]
`minecraft:` is actually a valid resource location referring to the file at `data/minecraft/loot_tables/.json`.

**Comment by ChenCMD** [comment]
> `minecraft:` (or simply `:`) is actually a valid resource location referring to the file at `data/minecraft/loot_tables/.json`.

If that's the case, then I think DHP should provide error and parsing, why not do it intentionally?

**Comment by SPGoding** [comment]
Oops seems like I misunderstood your issue

**Comment by SPGoding** [comment]
This should be fixed by Misode ([code](https://github.com/SPYGlassMC/SPYGlass/blob/04d10f98c7e05f69ddda6fe25e2656fd1698047a/packages/json/src/util.ts#L27)) due to the usage of `(.*)\.json`.
