### ISSUE TITLE
Enchantments autocomplete support

### ISSUE THREAD

**Issue by whitebear60** [SPYGlassMC/SPYGlass#813]
I think it would be great if Datapack Helper Plus will receive enchantments autocomplete support in NBT tags

https://user-images.githubusercontent.com/42472132/105355543-faa4fb80-5bfa-11eb-9908-eeb04fd84cc5.mov

**Comment by MulverineX** [comment]
The enchantment registry is available, as it's used in the `enchant` command, should be trivial to add.
