### ISSUE TITLE
Open sound name in Misode's MVP sounds tool

### ISSUE THREAD

**Issue by SPGoding** [SPYGlassMC/SPYGlass#814]
https://misode.github.io/sounds/

Perhaps we could pass in some query parameters to the link 🤔

See also [Discord message](https://discord.com/channels/666020457568403505/666020458453270535/802218543675605082).

**Comment by misode** [comment]
Query parameters are now supported, so DHP is free to use whenever it wants to.

https://misode.github.io/sounds/?sound=ambient.underwater.enter&pitch=1.7&volume=0.8

**Comment by SPGoding** [comment]
This is added in 43250ea3e785c012d64948f09d77991a68cd1d37.
