### ISSUE TITLE
Special strings inside data modify are not parsed

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/SPYGlass#824]
When using data modify on for example a command block, the command string is not parsed or interpreted like it usually happens, despite the tooltip recognizing the key as a command string.
![grafik](https://user-images.githubusercontent.com/12124394/106194433-20a83e00-61af-11eb-9fc9-0abdfceaa275.png)

This also affects blocks with json data, or things like the structure of a structure block

**Comment by SPGoding** [comment]
Duplicate of #400.
