### ISSUE TITLE
mod support

### ISSUE THREAD

**Issue by Goten87** [SPYGlassMC/SPYGlass#829]
so i have this plugin installed now and when i try to add modded items to the datapack it gives me errors

```Invalid option "appliedenergistics2:flour".```
```Invalid option "create:dough".```

its working ingame the crafting so my question is how can i add the mods to the plugin so they dont trow me errors anymore

**Comment by NeunEinser** [comment]
I think technically you can already use `#declare item ...`, but if you don't already have a good list where you can perform some regex on, that's not really a great option

**Comment by SPGoding** [comment]
Closing as this is quite out-of-scope ;/

**Comment by MulverineX** [comment]
Extended registries will be possible in the future with nbtdoc support & the plugin API, both seperate issues.

**Comment by MulverineX** [comment]
#834 #695 #830

**Comment by FreshAlacrity** [comment]
Having the same issue - how can I disable checking whether the options/items etc. are valid from the get-go?

**Comment by ChenCMD** [comment]
> Having the same issue - how can I disable checking whether the options/items etc. are valid from the get-go?

[You can change the settings](https://github.com/SpyglassMC/Spyglass/wiki/Lint-Rules#%EF%B8%8F-diagnostic-rules)
