### ISSUE TITLE
No autocomplete for selector

### ISSUE THREAD

**Issue by barraIhsan** [SPYGlassMC/SPYGlass#832]
Usually, there is autocomplete for text, translate, italic, color, bold, etc. But strange enough there is no auto complete for selector
![image](https://user-images.githubusercontent.com/57800056/107843899-9217fb80-6e01-11eb-88ce-8fd4a447ee26.png)

BUT when you type {"selector":""} there is an auto complete for it!
![image](https://user-images.githubusercontent.com/57800056/107843890-7f9dc200-6e01-11eb-97ba-4fb3de96dfff.png)
(for @s, @a, @e, @p, etc.)

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/113809669-3cd7d680-972e-11eb-81a1-25095c64b512.png)

This was fixed by Misode in the rewrite :tada:
