### ISSUE TITLE
Add initial support for mcdoc files

### ISSUE THREAD

**Issue by SPGoding** [SpyglassMC/Spyglass#834]
## mcdoc era

Specification for mcdoc can be found [here](https://spyglassmc.com/user/mcdoc).

Check list:
- [x] Parser.
- [x] Colorizer.
- [ ] Type checker.

## nbtdoc era

Specification for nbtdoc written by [Yurihaia](https://github.com/Yurihaia) could be found [here](https://github.com/Yurihaia/nbtdoc-rs/blob/master/docs/format.md).

Check list:
- [x] Parser (#839).
- [x] Colorizer (#848).
- [x] Type checker (#847).

**Comment by MulverineX** [comment]
trying to add this to milestone 4.1.0

**Comment by MulverineX** [comment]
@SPGoding to be clear here, the `mcdoc` directory within a datapack (alongside `data` & `pack.mcmeta`) is already fully supported? If that is the case, this should actually be milestone 4.0.0, and Completer/Formatter should be moved to another issue for milestone 4.1.0

**Comment by SPGoding** [comment]
> properly overrides/augments definitions from the internal `vanilla-mcdoc`

not sure about that part. i don't think `inject` is implemented yet, but dispatch should work fine.

**Comment by misode** [comment]
Initial support for mcdoc for v4.0 is finished. Further improvements will be tracked in #1208
