### ISSUE TITLE
uncaughtException Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by CWilsonTSP** [SPYGlassMC/SPYGlass#845]
When using this language server on nvim with coc, loading it causes the following error:
`uncaughtException Error: Header must provide a Content-Length property.`

I do not believe this is an issue with either coc or nvim, as I do not have these issues with other language servers.

For reference, here are links to a similar issues where the problem was something to do with the language server:
https://github.com/neoclide/coc-java/issues/136
https://github.com/EmmyLua/EmmyLua-LanguageServer/issues/21

**Comment by SPGoding** [comment]
As evidented [here](https://github.com/EmmyLua/EmmyLua-LanguageServer/issues/21#issuecomment-558874997), the language server shouldn't log messages unrelated to the LSP Protocol.

**Comment by SPGoding** [comment]
I'm gonna close this issue, as the upcoming language server fixed it. However, there would be a really long time before it actually comes to production, so this bug will still exist for a long time. Sorry for any inconvenience.
