### ISSUE TITLE
Renaming something declared private renames the symbol everywhere, instead of only in the own scope

### ISSUE THREAD

**Issue by NeunEinser** [SPYGlassMC/SPYGlass#860]
Example:
2 functions declare the following tag:
```mcfunction
#>
# Temporary tag
# @private
#declare tag test.temp
```

In case that tag is renamed in one of the functions using the renaming functionality, it will also be renamed in the other function.

**Comment by SPGoding** [comment]
This should already be fixed with the new `SymbolUtil`'s stack structure.
