### ISSUE TITLE
Color coding suddenly stopped working overnight.

### ISSUE THREAD

**Issue by MoutonDemocrate** [SPYGlassMC/SPYGlass#887]
My color coding stopped working for two files out of four in my datapack (on mcfunction files). I've tried to reboot my computer, regenerate the cache, reload the files, and nothing works. It worked yesterday...

Screenshots :
![Screenshot from 2021-06-14 11-40-03](https://user-images.githubusercontent.com/85873312/121873347-98ae7500-cd06-11eb-82a8-2ebfe18bb69d.png)
![Screenshot from 2021-06-14 11-39-55](https://user-images.githubusercontent.com/85873312/121873352-99dfa200-cd06-11eb-8b68-0b7d99edb815.png)

Any ideas about what's going on ?

**Comment by SPGoding** [comment]
This is weird. Does other features (like auto completion) work in those two files?

**Comment by MoutonDemocrate** [comment]
Strangely enough, it suddenly started working again, so it's not as much of
an issue as it was. However, it would still be nice to know why this
happened.

The autocompletion feature worked in all files, but for the not-colorcoded
ones, wherever I placed my cursor, it would act like it started a new
line...

**Comment by SPGoding** [comment]
I suspect there might be some other extensions interfering with it 🤔
