### ISSUE TITLE
Water Cauldron

### ISSUE THREAD

**Issue by Terrator24** [SPYGlassMC/SPYGlass#890]
in my sittuation, if you'll try to execute water_cauldron(like this-> execute if block ~ ~ ~ water_cauldron), the whole datapack isn't working(all the commands, functions, json files and etc). How can i fix this?

**Comment by SPGoding** [comment]
This is not the place for asking general data pack questions. You might want to go check out the [Minecraft Commands](https://discord.gg/QAFXFtZ) Discord server.
