### ISSUE TITLE
/replaceitem still recognized as valid 1.17 command

### ISSUE THREAD

**Issue by ThatBenKraft** [SPYGlassMC/SPYGlass#893]
As described, `replaceitem` doesn't throw an error when used in a 1.17 setting.

**Comment by SPGoding** [comment]
Is `datapack.env.cmdVersion` set to `1.17` as well?

**Comment by ThatBenKraft** [comment]
Yes.

**Comment by SPGoding** [comment]
Thanks, should be fixed now.

**Comment by SPGoding** [comment]
Actually no. The old behavior is done in order to provide quick fixes for updating `replaceitem` commands. I will release a new version to revert the changes.
