### ISSUE TITLE
Optional field syntax is not supported

### ISSUE THREAD

**Issue by SPGoding** [SPYGlassMC/SPYGlass#896]
See also Yurihaia/nbtdoc-rs@a0800c0ba2d9b1be24423f07d17cee85404c0c2e.

This will bring complexity to the nbtdoc type assignability checker. Right now any compound types are assignable to each other, as all fields are considered optional. This addition to the nbtdoc specification added a new concept of required fields, forcing the assignability checker to be aware of the required keys in each compound definition before checking the assignability between them.

**Comment by SPGoding** [comment]
Also a somehow related question: what does "optional" mean in this case? Does it mean optional when reading, or optional when writing to NBT?

**Comment by MulverineX** [comment]
Well this is kinda difficult to do as fulfilling required NBT can occur over multiple commands

**Comment by misode** [comment]
I think it's ok for Spyglass to ignore whether a field is marked as optional or not, and treat every field as if it were optional. The reason the optional field syntax was added is to allow future support to validate NBT files. In those cases it needs to differentiate between the required `id` field and the optional `tag` field in item compounds.
