### ISSUE TITLE
strictEntityTypeCheck error detected in wrong context

### ISSUE THREAD

**Issue by fludim** [SpyglassMC/Spyglass#897]
Version: 3.3.14

I get the below message as SPYGlass thinks I am trying to reference the default `id` in an entity's root nbt, when this instance of `id` is in a custom compound in an item:

Full message: `Failed to resolve namespaced ID “minecraft:`_whatever_`” in registry “minecraft:entity_type” (rule: “strictEntityTypeCheck”).`

Command: `execute if data entity @s SelectedItem.tag.namespaced_compound{id:"`_whatever_`"} ...`

**Comment by MulverineX** [comment]
Very strange. Will be fixed in v4.
