### ISSUE TITLE
The maximum distance of worldborder has been silently changed to 59999968 in 1.17

### ISSUE THREAD

**Issue by ChenCMD** [SPYGlassMC/SPYGlass#899]
To be precise, the maximum distance is twice the `max-world-size` in `server.properties`.

**Comment by SPGoding** [comment]
Nice catch! Though this doesn't affect v4 as it reads the [`commands.json`](https://github.com/Arcensoth/mcdata/blob/master/generated/reports/commands.json) file provided by Minecraft.
