### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by wessltov** [SPYGlassMC/SPYGlass#901]
Despite installing and even restarting VS code, this extension doesn't work for me.
I realize this is as good as nothing to go on, but I'm willing to provide any information that might be needed to to troubleshoot  this.
I'm sorry the inconvenience

**Comment by SPGoding** [comment]
Could you please make sure `mcfunction` is shown at the bottom-right corner of your status bar when you open your `mcfunction` file?

**Comment by wessltov** [comment]
> Could you please make sure `mcfunction` is shown at the bottom-right corner of your status bar when you open your `mcfunction` file?

Thank you for being willing to help!
It does show mcfuntion, but the only code suggestions it gives me are words that I already typed in that file

**Comment by wessltov** [comment]
> Please go to `Help -> About` to check your VS Code version, and make sure it's later than `1.44.0`. If it's outdated, use `Help -> Check for Updates...` to update your VS Code.
> 
> If that doesn't solve the issue, open a `mcfunction` file, press `Ctrl + Shift + P` to open the command palette, and go to `Output: Focus on Output View`, check if there's `Datapack Language Server` in the dropdown menu.
> 
> ![image](https://user-images.githubusercontent.com/15277496/128895376-c69bd436-70a5-4b95-85d0-c6c6f1e22082.png)
> 
> If yes, please check if there's any error-like message in that log.
> 
> If no, the extension wasn't activated, and I can't tell why :/

I thought I was already on the latest version, but looking at the output, I saw the following: 
`The language client requires VS Code version ^1.52.0 but received version 1.45.1`
Turns out I had accidentally updated regular Visual Studio, rather than Visual Studio Code. After updating, the extension works like a charm! Thank you so much for helping me!

**Comment by SPGoding** [comment]
Glad it's solved :D
