### ISSUE TITLE
Deepslate variants aren't inside the minecraft:block registry

### ISSUE THREAD

**Issue by BlauToad** [SPYGlassMC/SPYGlass#902]
These deepslate variants minecraft:deepslate_slab, minecraft:deepslate_stairs and minecraft:deepslate_wall aren't inside the minecraft:blocks registry:
![deepslate](https://user-images.githubusercontent.com/53124247/128756645-3f4d51d2-a9fe-43b4-bbe9-98d0c8aadbe8.png)

**Comment by SPGoding** [comment]
There's no such block. You might want `cobbled_deepslate_slab`, `polished_deepslate_slab`, `deepslate_brick_slab`, or `deepslate_tile_slab`.

**Comment by BlauToad** [comment]
Oh sorry, I coppied a list of blocks from mcstacker, I have to issue that there that these don't exist.
