### ISSUE TITLE
NBT tag DeathTime not recognized.

### ISSUE THREAD

**Issue by GreatMCGamer** [SPYGlassMC/SPYGlass#904]
Version: Data-Pack Helper Plus v3.3.14
App: VsCode
Platform: Windows 10

Example command for reproduction:
summon item_frame ~ ~-1 ~ {DeathTime:19,Tags:["tp"]}

Disclaimer: I don git it.

**Comment by SPGoding** [comment]
I don't think `item_frame` has that tag.
