### ISSUE TITLE
mcmeta pack format false error

### ISSUE THREAD

**Issue by niniemouse** [SPYGlassMC/SPYGlass#905]
when I open my .mcmeta file, the pack format number is underlined in red and the hint says that it expected a number between 7 and 7. So I have to leave the error hint there and keep my entry intact. I'm stuck with red file names though. It's not an emergency, just an observation ;)

![2021-09-03 20_37_13-pack mcmeta - ninierecipes (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/89825282/132076638-b616ac22-fc3d-4981-8faa-7a809f8712a8.jpg)
![2021-09-03 20_38_13-pack mcmeta - ninierecipes (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/89825282/132076676-6ca8c743-2b56-4c14-99a1-0ebe808f7c32.jpg)

**Comment by SPGoding** [comment]
Sorry for the unintuitive error message. Could you please try changing the version (`datapack.env.cmdVersion`, `datapack.env.dataVersion`, and `datapack.env.jsonVersion`) to `1.16` in VS Code's settings?

**Comment by niniemouse** [comment]
It worked! Thank you😁
