### ISSUE TITLE
DHP unavoidable "Invalid Option" error in worldgen BlockState provider with some 1.17 blocks

### ISSUE THREAD

**Issue by Bluperman949** [SpyglassMC/Spyglass#909]
Some newer blocks, such as Raw Gold, aren't recognized properly. For the strictBlockCheck rule, I can configure its severity to "information" in vscode settings so I don't get bombarded with errors, but for BlockState providers in worldgen json, there isn't a setting to configure the severity of invalid options, so I can't prevent this error.
![image](https://user-images.githubusercontent.com/42910681/140329255-bd1fc8db-5134-422d-b52b-996f2fa0d346.png)

**Comment by MulverineX** [comment]
Caching and/or data version bug. Will be fixed in v4.
