### ISSUE TITLE
language server: pack.mcmeta pack_format key not properly typed

### ISSUE THREAD

**Issue by winstonDeGreef** [SPYGlassMC/SPYGlass#910]
In the `pack.mcmeta` file in the root folder of a datapack, `pack.pack_format` only allows the number seven, but when developing datapacks for versions of minecrfaft other than 1.17, the value could be anywhere between 4 and 7. In the future 8+ is also possible.

**Comment by SPGoding** [comment]
Thanks for the report! You can change the version (`datapack.env.cmdVersion`, `datapack.env.dataVersion`, and `datapack.env.jsonVersion`) in the settings to something other than `1.17` to use other `pack_format` numbers. I know this isn't ideal but some effort have already been done in the v4 branch (#797).

**Comment by winstonDeGreef** [comment]
An option is to include this as the error message. "7 is the only valid value for pack.pack_format for 1.17, if you are developing for a different version, change datapack.env.cmdVersion, datapack.env.dataVersion, and datapack.env.jsonVersion in the settings to minecraft version you are developing for. (perhaps combine these options to datapack.env.minecraftVersion)
