### ISSUE TITLE
Request to publish the extension onto the Open VSX Registry

### ISSUE THREAD

**Issue by CubeTheThird** [SPYGlassMC/SPYGlass#912]
Haven't seen any mentions of this elsewhere, and hope I am not asking in the wrong place.

I am wondering if it would be possible to publish the previous iteration of the vscode extension (and eventually this one) on the [Open VSX Registry](https://open-vsx.org/). This will allow users to install it through the alternative marketplace, which is useful when the Microsoft one cannot be used.

**Comment by SPGoding** [comment]
Thanks! Most versions uploaded & pending namespace claim at EclipseFdn/open-vsx.org#760.
