### ISSUE TITLE
1.17 Gamerules Marked as fixed but are definitely not fixed:

### ISSUE THREAD

**Issue by InQuognito** [SPYGlassMC/SPYGlass#913]
Fixed.

_Originally posted by @SPGoding in https://github.com/SPYGlassMC/SPYGlass/issues/891#issuecomment-864491583_

**Comment by InQuognito** [comment]
![image](https://user-images.githubusercontent.com/44120299/146463283-c1d8d2fb-38b3-47d8-9cb4-1184d4991e00.png)

**Comment by SPGoding** [comment]
Please make sure `datapack.env.cmdVersion` is set correctly in your VS Code settings.

**Comment by InQuognito** [comment]
@SPGoding 
![image](https://user-images.githubusercontent.com/44120299/146647358-095a3a2a-fdd8-42f0-a2cf-13c007324cdd.png)
![image](https://user-images.githubusercontent.com/44120299/146647376-5237ed21-030b-42f0-8600-13770e2a9c23.png)

**Comment by SPGoding** [comment]
Oh sorry, my bad! It was fixed for 1.17 but not 1.18. Should be fixed in the latest version.
