### ISSUE TITLE
Deepslate and its variants aren't inside the minecraft:item and minecraft:block registry

### ISSUE THREAD

**Issue by dodomos** [SPYGlassMC/SPYGlass#914]
From what I can tell, the problem of deepslate and its variants not being registered correctly has existed since 1.17, please fix it.
![QQ图片20211227214004](https://user-images.githubusercontent.com/50882096/147477509-6383001f-458b-4570-ac45-0e08e8839ca5.png)
![QQ图片20211227214406](https://user-images.githubusercontent.com/50882096/147477515-17ff7229-7c8c-48ca-8606-5b4ceb027025.png)

**Comment by SPGoding** [comment]
GFW 把补全数据给墙了，让 NodeJS 走代理应该就行了。

或者也可以手动下载补全数据。

1. 在 VS Code 中按 `Ctrl + Shift + P`，搜索并切换到`输出视图`
2. 在输出视图的下拉框中选择 `Data-pack Language Server`
3. 拉到最上面，应该有一行类似 `[onInitialize] globalStoragePath = xxx` 的内容，把等号后面的路径复制出来。
4. 打开复制的路径，在里面创建文件夹 `1.17.1`（如果你在设置里 `datapack.env.dataVersion` 版本选的是 `1.18.1` 或者 `Latest release` 创建 `1.18.1`）
5. 下载如下文件并保存进新创建的文件夹
   - https://raw.githubusercontent.com/Arcensoth/mcdata/1.17.1/processed/reports/blocks/data.min.json 存成 `BlockDefinition.json`    
   - https://raw.githubusercontent.com/Arcensoth/mcdata/1.17.1/processed/reports/registries/data.min.json 存成 `Registry.json`
   - https://raw.githubusercontent.com/Yurihaia/mc-nbtdoc/1.17.1-gen/build/generated.json 存成 `Nbtdoc.json`
   - https://raw.githubusercontent.com/SPGoding/vanilla-datapack/1.17.1-summary/summary/flattened.min.json 存成 `NamespaceSummary.json`
   - （如果创建的文件夹文件名是 `1.18.1`，下载前把以上链接里的 `1.17.1` 都换成 `1.18.1`）
6. 重启 VS Code，应该好了。
