### ISSUE TITLE
tellraw command is not showing all the tags like "score", or "selector" and much more

### ISSUE THREAD

**Issue by ROUPIKS** [SpyglassMC/Spyglass#916]
In the previous version of DHP, there was more completion for the tags (like "score", "selector", "block" etc...) for tellraw commands. I think it is broken now or maybe there is something i'm missing
![tellraw completion](https://user-images.githubusercontent.com/97475039/148837403-b2da527e-7639-48f8-b7f8-7fcede62f69c.png)
.

**Comment by SPGoding** [comment]
Yeah it is broken right now, sorry about that. This will be fixed in the next major version (#832).

**Comment by ROUPIKS** [comment]
Thanks for the fast answer. Amazing job on the extension 👍 !
