### ISSUE TITLE
/loot insert <x> <y> <z> only accept integers, but datapack shows floats as valid option

### ISSUE THREAD

**Issue by InQuognito** [SpyglassMC/Spyglass#923]
![image](https://user-images.githubusercontent.com/44120299/157566758-34e2200e-a49a-4ef9-a305-3b834aed64e7.png)

![image](https://user-images.githubusercontent.com/44120299/157566790-d098d15b-41ce-4870-8d70-df377310318d.png)

**Comment by SPGoding** [comment]
Thanks for the report! Fixed in c12585860b2340daa57520abac3aca0bc2e2a389.

This isn't an urgent issue so I won't release a new version soon.

**Comment by InQuognito** [comment]
that was fast! no problem, keep up the amazing work! :)
