### ISSUE TITLE
custom_spawn_rules use either an integer or a list, not a compound

### ISSUE THREAD

**Issue by GrifterMage** [SpyglassMC/Spyglass#924]
DHP expects a compound tag for block_light_limit and sky_light_limit.

However, I was messing around with custom spawners and discovered that the block_light_limit and sky_light_limit tags for spawners do not actually use a compound tag as the Minecraft wiki says they do, but instead use either an integer for the exact light level required for spawns, or a list tag with two entries, for the lower and upper bounds of acceptable light levels respectively. Values are expected to be between 0-14 inclusive. If the two entries in the list are identical, they are collapsed into an integer value.

So, any of the following are valid entries for block_light_limit or sky_light_limit:

0
13
[0,14]
[3,7]
[12,13]

**Comment by SPGoding** [comment]
The [source in mc-nbtdoc](https://github.com/Yurihaia/mc-nbtdoc/blob/bb68242e528e4a8dfc5805af9bdbd571f3d922ff/minecraft/block/spawner.nbtdoc#L39-L49) is correct, so this seems like a bug with DHP v3 itself.

**Comment by GrifterMage** [comment]
I'm not sure I'm reading the mc-nbtdoc correctly, but I've done some additional testing, and as far as I can tell the doc is only partially correct. (As is my initial post--turns out I was wrong too.) It's a bit more complicated than that.

While the game will accept being given a compound value for either block_light_limit or sky_light_limit *if* it contains both min_inclusive and max_inclusive tags and both have valid values, it immediately collapses it into a two-element list. min_inclusive and max_inclusive never exist in the spawner's data as separate named tags--just as elements of the list.

So `data modify block ~ ~ ~ SpawnData.custom_spawn_rules.block_light_limit set value {min_inclusive:2,max_inclusive:3}` is valid, but `data modify block ~ ~ ~ SpawnData.custom_spawn_rules.block_light_limit.min_inclusive set value 2` is not. And because the list immediately collapses if both elements are the same, `data modify block ~ ~ ~ SpawnData.custom_spawn_rules.block_light_limit[0] set value 2` is only legal if the entry is already a list.

Also, it appears that block_light_limit and sky_light_limit accept value ranges from 0-15 inclusive, not 1-15. However, a list of `[0,15]` will immediately collapse and delete the tag entirely--it's the same result as if the tag didn't exist anyway.

**Comment by SPGoding** [comment]
Thanks for the detailed research! Unfortunately the nbtdoc format is not intended to represent the actual de/serialization process of Minecraft, so it can't accurately describe something being optional/mandatory or how one format would be collapsed to another format. I will fix the range to `0-15` though.
