### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by SPGoding** [SpyglassMC/Spyglass#929]
The project is called Spyglass, but the logo is a telescope.

If anyone's interested in helping, either a vector graphic or a pixel art will be greatly appreciated. Ideally it needs to include a spyglass and be clearly identifiable when presented at a 32×32 resolution in common display environments.

**Comment by NeunEinser** [comment]
Just take the approach every modern company takes and change to a generic logo with just the word (or maybe the letter S for a square logo) 🙂

**Comment by asd988** [comment]
Now the telescope is a spyglass...
![spyglass_icon](https://user-images.githubusercontent.com/81303551/163717979-d080d919-c997-48ac-9485-d72a215b41ed.svg)

**Comment by SPGoding** [comment]
@asd988 Thanks a lot! I might have just gotten used to the old logo but it looks kinda... empty? 

<details>
<summary>Expand to see failed attempts. Content Warning: extremely awful uncensored drafts</summary>
<details>
<summary>I was being serious.</summary>
<details>
<summary>Like, no, you do not want to look at them.</summary>
<details>
<summary>You have been warned.</summary>
<details>
<summary>Well, if you choose so...</summary>

![image](https://user-images.githubusercontent.com/15277496/163730760-60445b97-923c-450e-b33e-f0c977f08814.png) ![image](https://user-images.githubusercontent.com/15277496/163730783-7ea1c888-2dbc-4ed5-997b-6ee6907cb7eb.png) ![image](https://user-images.githubusercontent.com/15277496/163730801-de1e7b27-7cdb-4db4-b43c-9be232e41290.png) ![image](https://user-images.githubusercontent.com/15277496/163730812-154c8f53-e3ee-47eb-b093-5ae44710da01.png) ![image](https://user-images.githubusercontent.com/15277496/163730620-ab93836e-acfd-4699-b82e-c462b0ede0d5.png) ![image](https://user-images.githubusercontent.com/15277496/163730681-beb37d83-0f21-4137-8b0a-ac34b7d24432.png) ![image](https://user-images.githubusercontent.com/15277496/163730700-2beeddc0-df33-45a8-a09b-c6ed91833de4.png) ![image](https://user-images.githubusercontent.com/15277496/163730714-f0d10ea5-209f-4d06-8cd0-9c52bc773bf6.png)</details></details></details></details></details>

I think I will get used to it after a while. Thanks again for helping!
