### ISSUE TITLE
The Datapack Language Server server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by lucasbrasantos** [SpyglassMC/Spyglass#931]
![image](https://user-images.githubusercontent.com/78361979/160946433-910c87f2-ce5d-4710-892c-d3a543b219ea.png)

I'm using version 3.3.25 of the Data-pack Helper Plus extension in VSCode, every time I open vscode the extension doesn't load the code colors either, and the extension crashes

**Comment by SPGoding** [comment]
Could you please open the Command Palette (`Ctrl + Shift + P`), type and select `>Output: Focus on Output View`, select `Datapack Language Server` from the dropdown, and paste the log here?

Please note that some sensitive information (like your user name) may be in the log, and feel free to replace or remove them.

**Comment by DoOrDoNot2187** [comment]
I have exactly the same issue. These are the logs:
[Data-pack Helper Plus logs.txt](https://github.com/SpyglassMC/Spyglass/files/8385008/Data-pack.Helper.Plus.logs.txt)

**Comment by DoOrDoNot2187** [comment]
Yes, it is fixed now. Thank you very much!

**Comment by lucasbrasantos** [comment]
it is fixed now for me too. thankss

**Comment by SPGoding** [comment]
Great! Thanks for the report!
