### ISSUE TITLE
Autocomplete JSON values when halfway

### ISSUE THREAD

**Issue by kittech0** [SpyglassMC/Spyglass#932]
When there is already a string in json file, it doesnt autocompete 
What should do:
![image](https://user-images.githubusercontent.com/73485099/161093438-4d690d31-2434-40a5-abd7-f65daf64fec4.png)
But it doesnt
![image](https://user-images.githubusercontent.com/73485099/161093482-55d15763-ebfd-4449-aa41-17c5b303403a.png)
becuz to make it auto complete again i need to remove string and starts typing then

**Comment by MulverineX** [comment]
@kittech0 does pressing backspace then typing in `p` again make the autocomplete show up again? If so this isn't a bug
