### ISSUE TITLE
Add a built-in precompiler for multiline commands

### ISSUE THREAD

**Issue by asd988** [SpyglassMC/Spyglass#935]
I think there should be another file type something like `.mcfbetter`.

The only difference would be that in this one you can put line breaks inside commands and also the parameters wouldn't be separated by a singular space but rather white space. To separate commands you would need to put a semicolon at end of commands. Maybe even something like this `#* this is a comment *#` to put comments inside commands. 

When you would save this file then it will make a corresponding file to it in the same folder, but this one is the normal `.mcfunction`.

Tbh this should be inside the game itself, this just makes it so much less painful to read. I don't know if this is possible, but it would be so helpful.

**Comment by SPGoding** [comment]
Thanks for the suggestion. I don't plan to create a custom language in Spygass, as many custom languages/preprocessors/frameworks/tools created around data packs already exist:
* beet: https://mcbeet.dev
* mcbuild: https://mcbuild.dev/
* Onyx: https://github.com/DoubleF3lix/onyx
* Sandstone: https://www.sandstone.dev
* Trident: https://energyxxer.com/trident/

I'd recommend checking them out and picking one you're interested in. Right now there isn't a lot of editor support for them, but I'm planning on filling that gap with a future release of Spyglass.

**Comment by MulverineX** [comment]
Spyglass is not a precompiler. In the future it will however accept addons that can add support for such, like Trident, mclang, and others. Architecture for those addons, ie. whether they include integration with the compilers, is still up in the air. v3 will probably not release with support for addons but it includes progress towards that goal.

**Comment by asd988** [comment]
Oh okay, thanks I didn't know these even existed!
