### ISSUE TITLE
Changing a linting in spyglass.json does not apply until re-opening the file

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#937]
## Steps to Reproduce

1. Change a supported linting rule (ex. nameOfScoreholders) and use a scoreholder that does not match the defined pattern
  -> ❌ No warning is shown
2. Close and reopen the file
  -> ✅ A warning is shown.

## Expected behavior

Auto update warnings in open files when spyglass.json is changed/saved

**Comment by SPGoding** [comment]
Actually just updating the file content is enough to update all the errors.

**Comment by SPGoding** [comment]
The alternate here is to re-parse and re-check everything every time the config is changed. I think the current behavior is fine.
