### ISSUE TITLE
Linting rule nameOfNbtKey applies to string values

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#938]
![grafik](https://user-images.githubusercontent.com/12124394/162610339-5a5a477c-ba74-4a59-8880-b4b2f723871f.png)

## Expected behavior

The linting rule `nameOfNbtKey ` should only apply to keys, not to string values.

**Comment by NeunEinser** [comment]
Interestingly, the string inside the string list is not marked.

**Comment by SPGoding** [comment]
This was already fixed by 6c54dc142dbe51e87dde4926474e1c30144a391b :D
