### ISSUE TITLE
Linting rule nameOfNbtKey applies to vanilla nbt tags

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#939]
![grafik](https://user-images.githubusercontent.com/12124394/162610442-0856295e-97d4-4d63-8677-9f44e2f29bd0.png)

## Expected behavior

The linting rule should not apply in cases like that, as it's enforced by Minecraft.
Perhaps, in general this linting rule should not mark warnings in mcfunction files if an nbtdoc exists, and only in the nbtdoc itself in that case. If no nbtdoc exists, warning in mcfunction files is expected behavior.

**Comment by SPGoding** [comment]
Your proposed behavior has been implemented.

This linter now only checks the naming of a key in the following cases:

* This is a key definition in an nbtdoc compound definition block that is outside of the `::minecraft` module;
* This is a key used in an NBT compound tag that doesn't have an associated nbtdoc definition; OR
* This is a key used in an NBT path that doesn't have an associated nbtdoc definition.

The documentation on https://spyglassmc.com has been updated to reflect this change as well.

**Comment by NeunEinser** [comment]
I think I understood the docu, however it is hard to read for me, especially the OR at the end of the 2nd bullet point confused me into thinking this was `firstPoint AND (secondPoint OR thirdPoint)`, and it's hard to grasp the difference between 2 and 3, and I am still not 100% sure I understand it correctly.

May I suggest this phrasing

This linting rule applies if and only if at least one of these is true:

* The key is defined in a compound of an nbtdoc file outside of the `::minecraft` module.
* The key is part of a declared compund tag, but the key used is not part of the definition (usecase for example a custom tag within an item's `tag` tag)
* The key is part of a compound that is not declared anywhere.


The documentation also states that there is no way to have multiple config definitions within a workspace _yet_.

If you want to allow for example multiple packs within a workspace to use different configs, there needs to be a solution to not apply this linting rule to a tag _used_ within a pack that follows one linting rule, but _declared_ within a pack with a different, or none linting rule.

That's why my initial comment talks about the idea to only apply the linting rule in case of a declared tag only to the declaration rather than the usage.

**Comment by SPGoding** [comment]
Sorry if the documentation is confusing; it's a straight translation from the [code](https://github.com/SpyglassMC/Spyglass/blob/d537cedfb4346fe3d53fe4a3928b0778f838f459/packages/java-edition/src/index.ts#L60-L67). They are combined with "or" together as signaled by the semicolons. The only difference between 2 and 3 is that one's about compound tags (`{Foo: {Bar: 1}}`) while another is about nbt paths (`Foo.Bar`). 

A key is only checked at definition as suggested, or at every usage if it's not defined (this case could be removed so we only check keys at definitions?), but the suggested phrasing does not seem to indicate this. Not sure how to make it clearer. ~~And just thinking about multiple data packs under the workspace gives me pain.~~
