### ISSUE TITLE
Text within angle brackets in nbtdoc doc comments is disregared.

### ISSUE THREAD

**Issue by NeunEinser** [SpyglassMC/Spyglass#943]
![grafik](https://user-images.githubusercontent.com/12124394/162614811-ac38312f-fab2-42b4-b292-b1b69b879011.png)
![grafik](https://user-images.githubusercontent.com/12124394/162614826-2e42c8df-d514-49a8-98e3-f65deb32a29a.png)

**Comment by SPGoding** [comment]
It is treated as an XML tag inside a MarkDown string. TypeScript doc comments does this too.

![image](https://user-images.githubusercontent.com/15277496/162644690-cc790134-e542-484f-84eb-45d49a62e769.png)

**Comment by SPGoding** [comment]
> Oh, so would `&lt;` and `&gt;` work?

I would think so
