### ISSUE TITLE
Getting errors in "infiniburn" field in dimension_type

### ISSUE THREAD

**Issue by Apollo4O4** [SpyglassMC/Spyglass#958]
If someone has already reported this, I apologize. I haven't seen it anywhere else though, so idk. 

When I put ("infiniburn": "#minecraft:infiniburn_overworld"), I get an error that "Tags are not allowed here", even though they are. All my data versions are set to 1.19.

**Comment by misode** [comment]
This is caused by the `resource` string validator not using the `requireTag` parameter, which was recently added.

Relevant code: https://github.com/SpyglassMC/Spyglass/blob/release/3.3.0/src/utils/JsonSchemaHelper.ts#L453
