### ISSUE TITLE
Syntax Highlighting is slow | Datapack Helper Plus for VSCode

### ISSUE THREAD

**Issue by ApplecakeYT** [SpyglassMC/Spyglass#968]
When writing code for a .mcfunction file. It takes around 30-60seconds for the syntax highlighting to apply (Datapack Helper Plus). 
Here is the output I receive
`
<--- Last few GCs --->

[16392:0000079800324000]   130271 ms: Mark-sweep (reduce) 2750.6 (2830.3) -> 2540.2 (2627.8) MB, 23.7 / 0.0 ms  (average mu = 0.957, current mu = 0.970) last resort GC in old space requested
[16392:0000079800324000]   130333 ms: Mark-sweep (reduce) 2540.2 (2627.8) -> 2540.2 (2601.0) MB, 62.8 / 0.0 ms  (average mu = 0.899, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF638B64A16 node::Buffer::New+50294
 2: 00007FF638B64C1F node::OnFatalError+463
 3: 00007FF63B6789DA v8::Data::IsFixedArray+842
 4: 00007FF63B67892C v8::Data::IsFixedArray+668
 5: 00007FF63B749FD3 v8::JSHeapConsistency::CheckWrapper+68179
 6: 00007FF63A18F184 v8::CppHeap::GetHeapHandle+101364
 7: 00007FF63A178F38 v8::CppHeap::GetHeapHandle+10664
 8: 00007FF63A056CEB uv_random+6532091
 9: 00007FF63A2E1310 v8::internal::OSROptimizedCodeCache::EvictMarkedCode+65712
10: 00007FF63A3839F4 v8::internal::OSROptimizedCodeCache::EvictMarkedCode+731028
11: 00006C0307F0B23C 
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.
`
This error seems to be common when the highlighting is extra slow.
[Error - 1:28:54 PM] Connection to server is erroring. Shutting down server.

**Comment by MulverineX** [comment]
Will be fixed in v4.
