### ISSUE TITLE
Add possibility to exclude file paths

### ISSUE THREAD

**Issue by Leirof** [SpyglassMC/Spyglass#970]
On big datapacks that use systems such as search trees, the number of file is huge, and then the cache take hours to update... each time we load the datapack in VSC. It result of a high battery usage and a massive performance issue on the plugin (syntax highlight can take entire minutes to display correctly).

It would be great to be able to disable the cache, or just add the opened files to the cache.

**Comment by SPGoding** [comment]
Sorry about the performance issue with v3, although without caching it would probably be even worse.

Would you mind disabling the old extension and testing if this is still an issue with [this development version](https://cdn.discordapp.com/attachments/702320097020084296/962892835005272134/spyglass-test-channel-0.0.3.vsix)? The downloaded `vsix` file can be installed in VS Code's Extensions panel by clicking the three dots and selecting "Install from VSIX...".

The development version is a complete rewrite from the one available in Visual Studio Marketplace at the moment, so some functionalities are still missing, but I'd like to know how it compares to the release version in terms of performance.

Thanks!

**Comment by SPGoding** [comment]
If you're referring to the [Gunivers/Glib](https://github.com/Gunivers/Glib), upon some local testing there's an `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` error in the development version, so it's even worse than the release version :facepalm:

For the release version your best bet might be to use the `datapack.env.exclude` setting to exclude the search tree directories, restart VS Code, run the `datapack.regenerateCache` command, and restart VS Code again. Sorry for any inconvenience

Example setting:
```json
{
  "datapack.env.exclude": [
    "data/glib.block/functions/set/**/*.mcfunction"
  ]
}
```

**Comment by LeiRoF** [comment]
Haha, funny that you was able to spot the concerned project 😂
Ok, thx for this solution!

Btw, your solution give me an idea, that is maybe simple for you to implement: allow datapackers to add gitignore-like files in there projects that automatically exclude all the files and folders listed in

(editing directly the plugin setting is enough for us, but it constitue an additional instruction to give to the users of this datapack, and most of them will -as usual- not read it ^^')

**Comment by osfanbuff63** [comment]
> Btw, your solution give me an idea, that is maybe simple for you to implement: allow datapackers to add gitignore-like files in their projects that automatically exclude all the files and folders listed in
Completly agree, but maybe a option in `spyglass.json` if it doesn't exist already, or a gitignore-style format (maybe .vscode/.spyglass-ignore?)

**Comment by LeiRoF** [comment]
Hmmm, the .vscode folder is not always distributed in the final product.

In our case, the datapack is a library containing several modules that the user can chose (via a website) before the download in order to avoid downloading all the project (and then avoiding to download the docs, the generators, all the modules and this .vscode folder that is useless for the user).

**Comment by osfanbuff63** [comment]
```gitignore
.vscode
!.vscode/.spyglass-ignore
```
would probably work, but would you really need it in the final product? Mostly, I'd just distribute to the developers, unless you are meant to edit it yourself.

**Comment by SPGoding** [comment]
Thanks for the suggestion. I don't want to make excluding files a permanent solution -- ideally the extension should work just fine on large data packs.
