### ISSUE TITLE
Too many fake errors

### ISSUE THREAD

**Issue by B1BU** [SpyglassMC/Spyglass#972]
I can't open a single datapack on VSCode without my explorer going completely red and yellow from so many errors. My datapacks work fine but Datapack Helper Plus thinks there are a bunch of errors that do not exist, and I can't do anything about that cause I can't ignore error messages as far as I know. This is really annoying.

**Comment by ChenCMD** [comment]
Specifically, what kind of error is displayed?

**Comment by B1BU** [comment]
I found out it was a different extension that was causing the issues, sorry. I still get some random errors from time to time tho, if I see one of them again I'll open another issue.
