### ISSUE TITLE
The plugin doesn't know NULL

### ISSUE THREAD

**Issue by CraftingShadowDE** [SpyglassMC/Spyglass#974]
When you want to change the NBT value of an entity to NULL, for example removing a villagers profession:
```mcfunction
data merge entity @s {VillagerData:{level:1,profession:NULL}}
```
The plugin will tell you that NULL is not possible but this command works fine. Please fix that

**Comment by SPGoding** [comment]
`NULL` is not a thing.

**Comment by CraftingShadowDE** [comment]
oh, i didn't know that, thanks for telling me. i will just replace it with none then
