### ISSUE TITLE
VSCode Extension recognises nothing in datapack

### ISSUE THREAD

**Issue by WithLithum** [SpyglassMC/Spyglass#983]
The title might not be correct, sorry.

**As shown here, DHP does not recognise the block tag despite the block tag exists and works perfectly in-game.**
![image](https://user-images.githubusercontent.com/37800788/184242739-e72e8852-de0c-4f7b-9a1a-f869cf348b99.png)
![image](https://user-images.githubusercontent.com/37800788/184243020-d5f8b7aa-ff34-44c1-aa11-3e7386ccb18f.png)

Note that this does not only happen for tags:
![image](https://user-images.githubusercontent.com/37800788/184243319-d1580463-b542-425f-9226-03250bbb8cd1.png)
![image](https://user-images.githubusercontent.com/37800788/184243387-8cfeb88e-e5ea-4f43-aebd-4986ed16cdd6.png)

Here is a proof of the `pack.mcmeta` exists:
![image](https://user-images.githubusercontent.com/37800788/184243727-308bb1be-5e9c-4f07-9cdd-412f8e1867c7.png)

**Note:**
* This does not happen while I am working under Windows 11 (just on KUbuntu and Ubuntu)
* IntelliSense in tags and `pack.mcmeta` does not work
* I've tried regenerating the cache but that does not work (it made no difference)
* No errors in-game; Minecraft recognises everything correctly

**Environment:**
* Visual Studio Code 1.70.1
* KUbuntu 22.04 LTS (kernel 5.10.4-46-generic)

**Comment by WithLithum** [comment]
If you are looking for log, sadly, nothing is reported in the logs:
![image](https://user-images.githubusercontent.com/37800788/184245066-2d4cd44a-ad28-423d-9c94-a178ab947bc8.png)

**Comment by MulverineX** [comment]
This is a caching bug. Will be fixed in v4.
