### ISSUE TITLE
"reset" not recognized as a valid team color

### ISSUE THREAD

**Issue by msbmteam** [SpyglassMC/Spyglass#986]
The command `team modify <teamName> color reset` is a valid command, but this vscode extension marks it as a Problem:

> Expected “black”, “dark_blue”, “dark_green”, “dark_aqua”, “dark_red”, “dark_purple”, “gold”, “gray”, “dark_gray”, “blue”, “green”, “aqua”, “red”, “light_purple”, “yellow”, or “white” but got “reset”

![Data Pack Helper Plus vscode extension Issue #984](https://user-images.githubusercontent.com/343654/185517100-c573fb8d-0161-4a4f-bdb9-267a5a0f45b8.png)

**Comment by SPGoding** [comment]
Thanks for the report! Should have been fixed.
