### ISSUE TITLE
LootTable does not recognize Darkness effect ID

### ISSUE THREAD

**Issue by catter1** [SpyglassMC/Spyglass#987]
When creating a loot table with a very custom potion, the extension throws a problem with the darkness effect (id `33`) when put in the `set_nbt` function. Here is an example:
```
{
    "function": "minecraft:set_nbt",
    "tag": "{CustomPotionColor:1517120,HideFlags:32,Potion:\"minecraft:water\",CustomPotionEffects:[{Id:33,Amplifier:1,Duration:2147483647}]}"
}
```
Yes, the DatapackHelper+ version is set to 1.19. Here is the exact error:
```
Expected “21”, “11”, “14”, “1”, “15”, “19”, “26”, “27”, “28”, “4”, “6”, “32”, “16”, “12”, “30”, “31”, “9”, “22”, “2”, “7”, “18”, “5”, “29”, “17”, “3”, “8”, “23”, “24”, “25”, “20”, “13”, or “10” but got “33”.
```

**Comment by SPGoding** [comment]
Thanks for the report!

Eh numerical IDs. Very enjoyable to work with. Nice job Mojang.
