### ISSUE TITLE
Unknown key "PersistenceRequired"

### ISSUE THREAD

**Issue by Rusiink** [SpyglassMC/Spyglass#989]
![image](https://user-images.githubusercontent.com/112059660/190800738-69cf080f-62da-4a91-b4a9-db9067668f66.png)

As seen in the image, when the "PersistenceRequired" NBT is used, an error is raised.
It also marks the 'functions' that contain that NBT in yellow (in the workspace).

DHP works fine, it's just that.
((Thanks for such an excellent extension :D ))

**Comment by ChenCMD** [comment]
Are you have set it for armor_stand?
If so, throwing a warning is the expected behavior.

**Comment by SPGoding** [comment]
As ChenCMD noted, `PersistenceRequired` does not exist on armor stands. Showing a warning is the correct behavior.
