### ISSUE TITLE
Missing Frog "is_pregnant" Brain nbt and Allay CanDuplicate and DuplicationCooldown

### ISSUE THREAD

**Issue by EpyonProjects** [SpyglassMC/Spyglass#993]
Error when selecting the following nbt, `{Brain:memories:{minecraft:is_pregnant:{value:{}}}}`, or modifying data: `Brain.memories.is_pregnant`

The same for Allay's `CanDuplicate` and `DuplicationCooldown`

**Comment by MulverineX** [comment]
Will be fixed in v4. (fix incoming to mcdoc)
