### ISSUE TITLE
"Tried to access collection "tag/entity_type", but that doesn't exist." error being logged constantly

### ISSUE THREAD

**Issue by CreeperMagnet** [SpyglassMC/Spyglass#994]
I have absolutely no idea what causes this. I'll do some testing and see if I can narrow it down, unless the cause is already known.

![image](https://user-images.githubusercontent.com/45321954/199131317-b5a9c32d-afc2-4a68-910d-3e085286928e.png)

I'm also experiencing some syntax highlighting sluggishness, not sure if related. Will open another issue if it's not.

**Comment by MulverineX** [comment]
Will be fixed in v4.
