### ISSUE TITLE
Template pool error catching thinks "projection" is required for empty_pool_element

### ISSUE THREAD

**Issue by CreeperMagnet** [SpyglassMC/Spyglass#999]
![image](https://user-images.githubusercontent.com/45321954/203667092-00ed4fa3-e3a4-4269-b53b-5785ba911ad7.png)

This is incorrect behavior, as vanilla does not require projection for these elements. They're empty, so no projection is needed.

**Comment by MulverineX** [comment]
Will be fixed in v4.
